In [1]:
import pandas as pd

In [70]:
url = 'https://datosmacro.expansion.com/energia-y-medio-ambiente/emisiones-co2'

In [76]:
dfco2 = pd.read_html(url)[0]

In [77]:
dfco2

,Países,CO2 Totales Mt,CO2 Kg/1000$,CO2 t per capita,CO2 t per capita.1,Var.
0,España [+],231914,13,499,NaN,"9,18%"
1,Alemania [+],665884,15,806,NaN,"5,78%"
2,Reino Unido [+],335363,11,495,NaN,"4,59%"
3,Francia [+],302327,10,458,NaN,"7,88%"
4,Italia [+],319669,13,541,NaN,"8,38%"
...,...,...,...,...,...,...
179,Samoa [+],0360,31,178,NaN,"2,73%"
180,Yemen [+],12047,10,39,NaN,"1,55%"
181,Sudáfrica [+],435523,55,734,NaN,"0,70%"
182,Zambia [+],7011,11,36,NaN,"2,87%"
183,Zimbabue [+],12293,23,68,NaN,"5,17%"

In [3]:
df = pd.read_csv('global-data-on-sustainable-energy (1).csv')

In [4]:
df

,Entity,Year,Access to electricity (% of population),Access to clean fuels for cooking,Renewable-electricity-generating-capacity-per-capita,Financial flows to developing countries (US $),Renewable energy share in the total final energy consumption (%),Electricity from fossil fuels (TWh),Electricity from nuclear (TWh),Electricity from renewables (TWh),...,Primary energy consumption per capita (kWh/person),Energy intensity level of primary energy (MJ/$2017 PPP GDP),Value_co2_emissions_kt_by_country,Renewables (% equivalent primary energy),gdp_growth,gdp_per_capita,Density\n(P/Km2),Land Area(Km2),Latitude,Longitude
0,Afghanistan,2000,1.613591,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.561730,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.178635,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.572647,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.781475,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.747670,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [10]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

In [43]:
df = df.rename(columns={'entity': 'country'})

In [44]:
df

,country,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable-electricity-generating-capacity-per-capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,2000,1.61,6.2,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.07,7.2,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.41,8.2,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.74,9.5,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.06,10.9,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,42.56,29.8,62.88,30000.0,81.90,3.50,0.0,3.32,...,3227.68020,10.00,11020.000460,NaN,0.755869,1464.588957,38,390757.0,-19.015438,29.154857
3645,Zimbabwe,2017,44.18,29.8,62.33,5570000.0,82.46,3.05,0.0,4.30,...,3068.01150,9.51,10340.000150,NaN,4.709492,1235.189032,38,390757.0,-19.015438,29.154857
3646,Zimbabwe,2018,45.57,29.9,82.53,10000.0,80.23,3.73,0.0,5.46,...,3441.98580,9.83,12380.000110,NaN,4.824211,1254.642265,38,390757.0,-19.015438,29.154857
3647,Zimbabwe,2019,46.78,30.1,81.40,250000.0,81.50,3.66,0.0,4.58,...,3003.65530,10.47,11760.000230,NaN,-6.144236,1316.740657,38,390757.0,-19.015438,29.154857
3648,Zimbabwe,2020,52.75,30.4,80.61,30000.0,81.90,3.40,0.0,4.19,...,2680.13180,10.00,NaN,NaN,-6.248748,1214.509820,38,390757.0,-19.015438,29.154857

In [12]:
df.isna().sum()

entity                                                                 0
year                                                                   0
access_to_electricity_(%_of_population)                               10
access_to_clean_fuels_for_cooking                                    169
renewable-electricity-generating-capacity-per-capita                 931
financial_flows_to_developing_countries_(us_$)                      2089
renewable_energy_share_in_the_total_final_energy_consumption_(%)     194
electricity_from_fossil_fuels_(twh)                                   21
electricity_from_nuclear_(twh)                                       126
electricity_from_renewables_(twh)                                     21
low-carbon_electricity_(%_electricity)                                42
primary_energy_consumption_per_capita_(kwh/person)                     0
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)          207
value_co2_emissions_kt_by_country                                    428
renewables_(%_equivalent_primary_energy)                            2137
gdp_growth                                                           317
gdp_per_capita                                                       282
density\n(p/km2)                                                       1
land_area(km2)                                                         1
latitude                                                               1
longitude                                                              1
dtype: int64

In [18]:
df.head(50)

,entity,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable-electricity-generating-capacity-per-capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),...,primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2),latitude,longitude
0,Afghanistan,2000,1.613591,6.20,9.22,20000.0,44.99,0.16,0.0,0.31,...,302.59482,1.64,760.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
1,Afghanistan,2001,4.074574,7.20,8.86,130000.0,45.60,0.09,0.0,0.50,...,236.89185,1.74,730.000000,NaN,NaN,NaN,60,652230.0,33.939110,67.709953
2,Afghanistan,2002,9.409158,8.20,8.47,3950000.0,37.83,0.13,0.0,0.56,...,210.86215,1.40,1029.999971,NaN,NaN,179.426579,60,652230.0,33.939110,67.709953
3,Afghanistan,2003,14.738506,9.50,8.09,25970000.0,36.66,0.31,0.0,0.63,...,229.96822,1.40,1220.000029,NaN,8.832278,190.683814,60,652230.0,33.939110,67.709953
4,Afghanistan,2004,20.064968,10.90,7.75,NaN,44.24,0.33,0.0,0.56,...,204.23125,1.20,1029.999971,NaN,1.414118,211.382074,60,652230.0,33.939110,67.709953
5,Afghanistan,2005,25.390894,12.20,7.51,9830000.0,33.88,0.34,0.0,0.59,...,252.06912,1.41,1549.999952,NaN,11.229715,242.031313,60,652230.0,33.939110,67.709953
6,Afghanistan,2006,30.718690,13.85,7.40,10620000.0,31.89,0.20,0.0,0.64,...,304.42090,1.50,1759.999990,NaN,5.357403,263.733602,60,652230.0,33.939110,67.709953
7,Afghanistan,2007,36.051010,15.30,7.25,15750000.0,28.78,0.20,0.0,0.75,...,354.27990,1.53,1769.999981,NaN,13.826320,359.693158,60,652230.0,33.939110,67.709953
8,Afghanistan,2008,42.400000,16.70,7.49,16170000.0,21.17,0.19,0.0,0.54,...,607.83350,1.94,3559.999943,NaN,3.924984,364.663542,60,652230.0,33.939110,67.709953
9,Afghanistan,2009,46.740050,18.40,7.50,9960000.0,16.53,0.16,0.0,0.78,...,975.04816,2.25,4880.000114,NaN,21.390528,437.268740,60,652230.0,33.939110,67.709953
10,Afghanistan,2010,42.700000,20.00,8.27,36500000.0,15.15,0.19,0.0,0.75,...,1182.89200,2.46,7110.000134,NaN,14.362441,543.306526,60,652230.0,33.939110,67.709953
11,Afghanistan,2011,43.222020,21.80,8.13,28690000.0,12.61,0.18,0.0,0.60,...,1436.11430,3.23,8930.000305,NaN,0.426355,591.190030,60,652230.0,33.939110,67.709953
12,Afghanistan,2012,69.100000,23.00,9.29,62630000.0,15.36,0.14,0.0,0.74,...,1324.12110,2.61,8079.999924,NaN,12.752287,638.845852,60,652230.0,33.939110,67.709953
13,Afghanistan,2013,68.290650,24.80,9.10,268460000.0,16.86,0.22,0.0,0.89,...,1060.79260,2.46,5989.999771,NaN,5.600745,624.315454,60,652230.0,33.939110,67.709953
14,Afghanistan,2014,89.500000,26.10,8.95,6940000.0,18.93,0.16,0.0,1.00,...,868.57620,2.25,4880.000114,NaN,2.724543,614.223342,60,652230.0,33.939110,67.709953
15,Afghanistan,2015,71.500000,27.40,8.79,4890000.0,17.53,0.15,0.0,1.03,...,970.08030,2.37,5949.999809,NaN,1.451315,556.007221,60,652230.0,33.939110,67.709953
16,Afghanistan,2016,97.700000,28.60,9.87,860000.0,19.92,0.15,0.0,1.06,...,862.79114,2.24,5300.000191,NaN,2.260314,512.012778,60,652230.0,33.939110,67.709953
17,Afghanistan,2017,97.700000,29.70,9.79,50330000.0,19.21,0.18,0.0,1.09,...,829.31195,2.30,4780.000210,NaN,2.647003,516.679862,60,652230.0,33.939110,67.709953
18,Afghanistan,2018,96.616135,30.90,9.55,70100000.0,17.96,0.20,0.0,0.97,...,924.25085,2.44,6070.000172,NaN,1.189228,485.668419,60,652230.0,33.939110,67.709953
19,Afghanistan,2019,97.700000,31.90,9.58,4620000.0,18.51,0.18,0.0,0.89,...,802.61255,2.41,6079.999924,NaN,3.911603,494.179350,60,652230.0,33.939110,67.709953
20,Afghanistan,2020,97.700000,33.20,9.35,NaN,NaN,0.12,0.0,0.68,...,702.88800,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0,33.939110,67.709953
21,Albania,2000,100.000000,38.20,NaN,NaN,NaN,0.14,0.0,4.55,...,9029.43750,4.13,3170.000000,NaN,6.946217,1126.683340,105,28748.0,41.153332,20.168331
22,Albania,2001,100.000000,40.50,NaN,NaN,NaN,0.13,0.0,3.52,...,8635.53200,3.89,3230.000000,NaN,8.293313,1281.659826,105,28748.0,41.153332,20.168331
23,Albania,2002,100.000000,43.20,NaN,NaN,NaN,0.16,0.0,3.48,...,9443.55500,4.10,3759.999990,NaN,4.536524,1425.124219,105,28748.0,41.153332,20.168331
24,Albania,2003,100.000000,46.40,NaN,NaN,NaN,0.10,0.0,5.12,...,10756.61200,3.80,4070.000172,NaN,5.528637,1846.120121,105,28748.0,41.153332,20.168331
25,Albania,2004,100.000000,49.00,NaN,NaN,NaN,0.13,0.0,5.41,...,11586.95100,3.96,4250.000000,NaN,5.514668,2373.581292,105,28748.0,41.153332,20.168331
26,Albania,2005,100.000000,51.90,NaN,NaN,NaN,0.07,0.0,5.32,...,11545.61600,3.75,4030.000210,NaN,5.526424,2673.786584,105,28748.0,41.153332,20.168331
27,Albania,2006,100.000000,54.80,NaN,NaN,NaN,0.09,0.0,4.95,...,10976.72800,3.46,4010.000229,NaN,5.902659,2972.742924,105,28748.0,41.153332,20.168331
28,Albania,2007,100.000000,58.10,NaN,NaN,NaN,0.07,0.0,2.76,...,9534.87400,3.12,4139.999866,NaN,5.983260,3595.038057,105,28748.0,41.153332,20.168331
29,Albania,2008,100.000000,60.80,NaN,NaN,NaN,0.07,0.0,3.76,...,10499.32800,3.01,4079.999924,NaN,7.500041,4370.539925,105,28748.0,41.153332,20.168331
30,Albania,2009,100.000000,63.60,NaN,NaN,NaN,0.00,0.0,5.20,...,11524.42800,2.98,4219.999790,NaN,3.354289,4114.134899,105,28748.0,41.153332,20.168331
31,Albania,2010,100.000000,66.50,NaN,NaN,NaN,0.00,0.0,7.49,...,12377.50400,2.85,4449.999809,NaN,3.706938,4094.348386,105,28748.0,41.153332,20.168331
32,Albania,2011,100.000000,68.90,NaN,NaN,NaN,0.06,0.0,4.09,...,10854.64900,2.91,4849.999905,NaN,2.545406,4437.142612,105,28748.0,41.153332,20.168331
33,Albania,2012,99.900000,71.30,NaN,NaN,NaN,0.00,0.0,4.68,...,10652.80900,2.57,4360.000134,NaN,1.417243,4247.630047,105,28748.0,41.153332,20.168331
34,Albania,2013,100.000000,73.15,NaN,NaN,NaN,0.00,0.0,6.89,...,13392.77400,2.96,4440.000057,NaN,1.002018,4413.062005,105,28748.0,41.153332,20.168331
35,Albania,2014,99.950000,74.60,NaN,NaN,NaN,0.00,0.0,4.68,...,11809.46100,2.93,4820.000172,NaN,1.774449,4578.633208,105,28748.0,41.153332,20.168331
36,Albania,2015,99.980000,76.20,NaN,NaN,NaN,0.00,0.0,5.84,...,11824.31400,2.69,4619.999886,NaN,2.218726,3952.802538,105,28748.0,41.153332,20.168331
37,Albania,2016,99.890000,77.80,NaN,NaN,NaN,0.00,0.0,7.70,...,13823.74800,2.68,4480.000019,NaN,3.314981,4124.055390,105,28748.0,41.153332,20.168331
38,Albania,2017,99.890000,78.70,NaN,NaN,NaN,0.00,0.0,4.48,...,12802.36000,2.69,5139.999866,NaN,3.802227,4531.019374,105,28748.0,41.153332,20.168331
39,Albania,2018,100.000000,79.80,NaN,NaN,NaN,0.00,0.0,8.47,...,14609.70100,2.57,5110.000134,NaN,4.019360,5287.663694,105,28748.0,41.153332,20.168331
40,Albania,2019,100.000000,80.70,NaN,NaN,NaN,0.00,0.0,5.17,...,11585.55500,2.50,4829.999924,NaN,2.113420,5395.659532,105,28748.0,41.153332,20.168331
41,Albania,2020,100.000000,81.30,NaN,NaN,NaN,0.00,0.0,5.31,...,11158.00300,NaN,NaN,NaN,-3.955398,5246.292306,105,28748.0,41.153332,20.168331
42,Algeria,2000,98.973100,97.10,8.91,NaN,0.43,23.84,0.0,0.05,...,9746.52400,4.18,80050.000000,0.053235,3.800000,1765.027146,18,2381741.0,28.033886,1.659626
43,Algeria,2001,98.966870,97.30,8.79,810000.0,0.43,24.96,0.0,0.07,...,9961.64000,4.07,78650.000000,0.065218,3.000000,1740.606654,18,2381741.0,28.033886,1.659626
44,Algeria,2002,98.953060,97.80,8.68,310000.0,0.51,25.94,0.0,0.06,...,10180.35000,4.12,82400.001530,0.051677,5.600000,1781.828908,18,2381741.0,28.033886,1.659626
45,Algeria,2003,98.934010,98.00,8.57,90000.0,0.47,27.54,0.0,0.26,...,10510.46100,4.08,88190.002440,0.228104,7.200000,2103.381291,18,2381741.0,28.033886,1.659626
46,Algeria,2004,98.912080,98.20,8.46,140000.0,0.44,29.14,0.0,0.25,...,10759.02200,3.96,89489.997860,0.206787,4.300000,2610.185422,18,2381741.0,28.033886,1.659626
47,Algeria,2005,98.889610,98.50,8.34,160000.0,0.58,31.36,0.0,0.55,...,11113.72300,3.90,94190.002440,0.434119,5.900000,3113.094883,18,2381741.0,28.033886,1.659626
48,Algeria,2006,98.869010,98.70,7.42,NaN,0.41,32.90,0.0,0.22,...,11341.98000,4.10,99809.997560,0.163272,1.700000,3478.710002,18,2381741.0,28.033886,1.659626
49,Algeria,2007,98.852936,98.80,7.30,NaN,0.41,34.75,0.0,0.22,...,11759.70100,4.21,102750.000000,0.159905,3.400000,3950.512993,18,2381741.0,28.033886,1.659626

In [21]:
df['access_to_electricity_(%_of_population)'] = df['access_to_electricity_(%_of_population)'].round(2)

In [34]:
df['year'][0]

2000

In [38]:
df.iloc[0][2]

1.61

In [32]:
df.values

array([['Afghanistan', 2000, 1.61, ..., 652230.0, 33.93911, 67.709953],
       ['Afghanistan', 2001, 4.07, ..., 652230.0, 33.93911, 67.709953],
       ['Afghanistan', 2002, 9.41, ..., 652230.0, 33.93911, 67.709953],
       ...,
       ['Zimbabwe', 2018, 45.57, ..., 390757.0, -19.015438, 29.154857],
       ['Zimbabwe', 2019, 46.78, ..., 390757.0, -19.015438, 29.154857],
       ['Zimbabwe', 2020, 52.75, ..., 390757.0, -19.015438, 29.154857]],
      dtype=object)

In [46]:
df.loc[20: 3700: 21, 
        'country': 'land_area(km2)':1]

,country,year,access_to_electricity_(%_of_population),access_to_clean_fuels_for_cooking,renewable-electricity-generating-capacity-per-capita,financial_flows_to_developing_countries_(us_$),renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low-carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,renewables_(%_equivalent_primary_energy),gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
20,Afghanistan,2020,97.70,33.2,9.35,NaN,NaN,0.12,0.0,0.68,85.000000,702.8880,NaN,NaN,NaN,-2.351101,516.747871,60,652230.0
41,Albania,2020,100.00,81.3,NaN,NaN,NaN,0.00,0.0,5.31,100.000000,11158.0030,NaN,NaN,NaN,-3.955398,5246.292306,105,28748.0
62,Algeria,2020,99.80,99.7,15.64,NaN,NaN,72.01,0.0,0.72,0.989963,14933.8070,NaN,NaN,0.297899,-5.100000,3306.858208,18,2381741.0
83,Angola,2020,46.89,50.2,115.43,NaN,NaN,4.49,0.0,12.10,72.935500,3527.1600,NaN,NaN,NaN,-5.399987,1776.166868,26,1246700.0
104,Antigua and Barbuda,2020,100.00,100.0,167.98,NaN,NaN,0.31,0.0,0.02,6.060606,27785.2270,NaN,NaN,NaN,-20.192371,13992.744480,223,443.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3548,Uzbekistan,2004,99.70,84.6,67.15,220000.0,1.05,38.48,0.0,8.92,18.818565,21485.6100,23.290000,124839.996300,3.319612,7.449001,465.119887,79,447400.0
3569,Vanuatu,2004,29.31,15.1,2.94,NaN,64.06,0.04,0.0,0.00,0.000000,1804.7319,3.030000,70.000000,NaN,3.987393,1788.122206,25,12189.0
3590,Yemen,2004,49.59,57.4,0.00,110000.0,0.75,4.10,0.0,0.00,0.000000,3811.3972,3.160727,NaN,NaN,NaN,NaN,56,527968.0
3611,Zambia,2004,20.30,15.3,150.84,2550000.0,89.28,0.07,0.0,8.39,99.172585,3012.9995,11.290000,2109.999895,NaN,7.032395,538.591553,25,752618.0
3632,Zimbabwe,2004,35.69,32.2,62.38,NaN,81.58,3.63,0.0,5.78,61.424020,4045.2322,11.900000,9770.000458,NaN,-5.807538,482.998451,38,390757.0

In [48]:
df.nunique()

country                                                              176
year                                                                  21
access_to_electricity_(%_of_population)                             1663
access_to_clean_fuels_for_cooking                                    896
renewable-electricity-generating-capacity-per-capita                2110
financial_flows_to_developing_countries_(us_$)                      1017
renewable_energy_share_in_the_total_final_energy_consumption_(%)    2587
electricity_from_fossil_fuels_(twh)                                 1859
electricity_from_nuclear_(twh)                                       547
electricity_from_renewables_(twh)                                   1533
low-carbon_electricity_(%_electricity)                              2647
primary_energy_consumption_per_capita_(kwh/person)                  3628
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         1044
value_co2_emissions_kt_by_country                                   2397
renewables_(%_equivalent_primary_energy)                            1455
gdp_growth                                                          3320
gdp_per_capita                                                      3367
density\n(p/km2)                                                     124
land_area(km2)                                                       175
latitude                                                             175
longitude                                                            175
dtype: int64

In [50]:
df.country.unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bosnia and Herzegovina', 'Botswana',
       'Brazil', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
       'Cameroon', 'Canada', 'Cayman Islands', 'Central African Republic',
       'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo',
       'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czechia', 'Denmark',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France',
       'French Guiana', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana',
       'Greece', 'Grenada', 'Guatemala', 'Guinea', 'Guinea-Bissau',
       'Guyana', 'Haiti', 'Honduras', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iraq', 'Ireland', 'Israel', 'Italy', 'Jamaica',
       'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati', 'Kuwait',
       'Kyrgyzstan', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia',
       'Maldives', 'Mali', 'Malta', 'Mauritania', 'Mauritius', 'Mexico',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia',
       'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia',
       'Norway', 'Oman', 'Pakistan', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Romania', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden', 'Switzerland',
       'Tajikistan', 'Thailand', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Turkmenistan', 'Tuvalu', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Yemen', 'Zambia', 'Zimbabwe'],
      dtype=object)

In [52]:
valores_nulos = df[df['access_to_electricity_(%_of_population)'].isnull()]

In [65]:
df = df.drop((['financial_flows_to_developing_countries_(us_$)','renewables_(%_equivalent_primary_energy)','access_to_clean_fuels_for_cooking','longitude','latitude','access_to_electricity_(%_of_population)','access_to_clean_fuels_for_cooking']), axis=1)

KeyError: "['access_to_clean_fuels_for_cooking', 'longitude', 'latitude', 'access_to_electricity_(%_of_population)', 'access_to_clean_fuels_for_cooking'] not found in axis"

In [66]:
df = df.drop((['financial_flows_to_developing_countries_(us_$)','renewables_(%_equivalent_primary_energy)']), axis=1)

In [67]:
df

,country,year,renewable-electricity-generating-capacity-per-capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low-carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [68]:
df.isna().sum()

country                                                               0
year                                                                  0
renewable-electricity-generating-capacity-per-capita                931
renewable_energy_share_in_the_total_final_energy_consumption_(%)    194
electricity_from_fossil_fuels_(twh)                                  21
electricity_from_nuclear_(twh)                                      126
electricity_from_renewables_(twh)                                    21
low-carbon_electricity_(%_electricity)                               42
primary_energy_consumption_per_capita_(kwh/person)                    0
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         207
value_co2_emissions_kt_by_country                                   428
gdp_growth                                                          317
gdp_per_capita                                                      282
density\n(p/km2)                                                      1
land_area(km2)                                                        1
dtype: int64

In [69]:
df['renewable-electricity-generating-capacity-per-capita'].head(60)

0      9.22
1      8.86
2      8.47
3      8.09
4      7.75
5      7.51
6      7.40
7      7.25
8      7.49
9      7.50
10     8.27
11     8.13
12     9.29
13     9.10
14     8.95
15     8.79
16     9.87
17     9.79
18     9.55
19     9.58
20     9.35
21      NaN
22      NaN
23      NaN
24      NaN
25      NaN
26      NaN
27      NaN
28      NaN
29      NaN
30      NaN
31      NaN
32      NaN
33      NaN
34      NaN
35      NaN
36      NaN
37      NaN
38      NaN
39      NaN
40      NaN
41      NaN
42     8.91
43     8.79
44     8.68
45     8.57
46     8.46
47     8.34
48     7.42
49     7.30
50     6.64
51     6.44
52     7.02
53     6.89
54     6.76
55     6.62
56     6.78
57     7.85
58    11.88
59    16.02
Name: renewable-electricity-generating-capacity-per-capita, dtype: float64

In [78]:
df

,country,year,renewable-electricity-generating-capacity-per-capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low-carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [79]:
df.to_csv('Energia.csv')