In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
df = pd.read_csv('Energia2.csv')

In [4]:
df

,country,year,renewable-electricity-generating-capacity-per-capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low-carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [5]:
df.columns = df.columns.str.lower().str.replace('-', '_')

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [6]:
df.isna().sum()

country                                                               0
year                                                                  0
renewable_electricity_generating_capacity_per_capita                931
renewable_energy_share_in_the_total_final_energy_consumption_(%)    194
electricity_from_fossil_fuels_(twh)                                  21
electricity_from_nuclear_(twh)                                      126
electricity_from_renewables_(twh)                                    21
low_carbon_electricity_(%_electricity)                               42
primary_energy_consumption_per_capita_(kwh/person)                    0
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         207
value_co2_emissions_kt_by_country                                   428
gdp_growth                                                          317
gdp_per_capita                                                      282
density\n(p/km2)                                                      1
land_area(km2)                                                        1
dtype: int64

In [7]:
df['renewable_electricity_generating_capacity_per_capita'].tail(60)

3589      0.00
3590      0.00
3591      0.00
3592      0.00
3593      0.00
3594      0.04
3595      0.04
3596      0.04
3597      0.05
3598      0.06
3599      0.09
3600      0.19
3601      2.26
3602      2.94
3603      3.59
3604      8.77
3605      8.57
3606      8.48
3607    173.03
3608    168.56
3609    164.26
3610    154.77
3611    150.84
3612    146.95
3613    143.12
3614    134.61
3615    133.35
3616    130.26
3617    142.25
3618    138.01
3619    134.28
3620    154.25
3621    149.51
3622    145.55
3623    148.58
3624    144.85
3625    140.76
3626    142.11
3627    138.23
3628     61.42
3629     61.20
3630     62.72
3631     62.58
3632     62.38
3633     62.09
3634     61.68
3635     61.18
3636     67.35
3637     66.60
3638     65.79
3639     66.20
3640     65.14
3641     64.44
3642     63.38
3643     63.54
3644     62.88
3645     62.33
3646     82.53
3647     81.40
3648     80.61
Name: renewable_electricity_generating_capacity_per_capita, dtype: float64

In [8]:
valores_nulos = df[df['renewable_electricity_generating_capacity_per_capita'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
21,Albania,2000,NaN,NaN,0.14,0.0,4.55,97.014930,9029.4375,4.13,3170.000000,6.946217,1126.683340,105,28748.0
22,Albania,2001,NaN,NaN,0.13,0.0,3.52,96.438354,8635.5320,3.89,3230.000000,8.293313,1281.659826,105,28748.0
23,Albania,2002,NaN,NaN,0.16,0.0,3.48,95.604390,9443.5550,4.10,3759.999990,4.536524,1425.124219,105,28748.0
24,Albania,2003,NaN,NaN,0.10,0.0,5.12,98.084300,10756.6120,3.80,4070.000172,5.528637,1846.120121,105,28748.0
25,Albania,2004,NaN,NaN,0.13,0.0,5.41,97.653430,11586.9510,3.96,4250.000000,5.514668,2373.581292,105,28748.0
26,Albania,2005,NaN,NaN,0.07,0.0,5.32,98.701300,11545.6160,3.75,4030.000210,5.526424,2673.786584,105,28748.0
27,Albania,2006,NaN,NaN,0.09,0.0,4.95,98.214280,10976.7280,3.46,4010.000229,5.902659,2972.742924,105,28748.0
28,Albania,2007,NaN,NaN,0.07,0.0,2.76,97.526505,9534.8740,3.12,4139.999866,5.983260,3595.038057,105,28748.0
29,Albania,2008,NaN,NaN,0.07,0.0,3.76,98.172325,10499.3280,3.01,4079.999924,7.500041,4370.539925,105,28748.0
30,Albania,2009,NaN,NaN,0.00,0.0,5.20,100.000000,11524.4280,2.98,4219.999790,3.354289,4114.134899,105,28748.0
31,Albania,2010,NaN,NaN,0.00,0.0,7.49,100.000000,12377.5040,2.85,4449.999809,3.706938,4094.348386,105,28748.0
32,Albania,2011,NaN,NaN,0.06,0.0,4.09,98.554214,10854.6490,2.91,4849.999905,2.545406,4437.142612,105,28748.0
33,Albania,2012,NaN,NaN,0.00,0.0,4.68,100.000000,10652.8090,2.57,4360.000134,1.417243,4247.630047,105,28748.0
34,Albania,2013,NaN,NaN,0.00,0.0,6.89,100.000000,13392.7740,2.96,4440.000057,1.002018,4413.062005,105,28748.0
35,Albania,2014,NaN,NaN,0.00,0.0,4.68,100.000000,11809.4610,2.93,4820.000172,1.774449,4578.633208,105,28748.0
36,Albania,2015,NaN,NaN,0.00,0.0,5.84,100.000000,11824.3140,2.69,4619.999886,2.218726,3952.802538,105,28748.0
37,Albania,2016,NaN,NaN,0.00,0.0,7.70,100.000000,13823.7480,2.68,4480.000019,3.314981,4124.055390,105,28748.0
38,Albania,2017,NaN,NaN,0.00,0.0,4.48,100.000000,12802.3600,2.69,5139.999866,3.802227,4531.019374,105,28748.0
39,Albania,2018,NaN,NaN,0.00,0.0,8.47,100.000000,14609.7010,2.57,5110.000134,4.019360,5287.663694,105,28748.0
40,Albania,2019,NaN,NaN,0.00,0.0,5.17,100.000000,11585.5550,2.50,4829.999924,2.113420,5395.659532,105,28748.0
41,Albania,2020,NaN,NaN,0.00,0.0,5.31,100.000000,11158.0030,NaN,NaN,-3.955398,5246.292306,105,28748.0
168,Australia,2000,NaN,8.42,181.05,0.0,17.11,8.634437,68632.9600,6.16,339450.000000,3.912428,21697.708480,3,7741220.0
169,Australia,2001,NaN,8.37,194.33,0.0,17.40,8.218014,68338.2800,5.91,345640.000000,2.038301,19527.323580,3,7741220.0
170,Australia,2002,NaN,8.74,197.29,0.0,17.35,8.083303,68892.7800,5.89,353369.995100,4.014527,20117.788890,3,7741220.0
171,Australia,2003,NaN,7.15,195.13,0.0,18.50,8.659832,69082.7900,5.78,352579.986600,3.110325,23492.405170,3,7741220.0
172,Australia,2004,NaN,6.68,203.66,0.0,19.41,8.701304,70486.3200,5.65,365809.997600,4.205447,30513.941740,3,7741220.0
173,Australia,2005,NaN,6.71,195.95,0.0,19.75,9.156236,69917.1640,5.52,370089.996300,3.160338,34080.999900,3,7741220.0
174,Australia,2006,NaN,6.85,198.72,0.0,21.19,9.635760,71863.7600,5.58,375489.990200,2.726893,36117.487980,3,7741220.0
175,Australia,2007,NaN,6.95,208.59,0.0,20.93,9.119031,72304.6950,5.52,385750.000000,3.768488,41001.142980,3,7741220.0
176,Australia,2008,NaN,6.79,211.06,0.0,18.49,8.054890,72089.3400,5.53,388940.002400,3.577015,49654.910600,3,7741220.0
177,Australia,2009,NaN,7.15,216.42,0.0,18.32,7.804379,69689.8400,5.43,395290.008500,1.866832,42783.322570,3,7741220.0
178,Australia,2010,NaN,8.16,212.50,0.0,21.13,9.044215,68523.8750,5.33,387540.008500,2.172337,52087.972290,3,7741220.0
179,Australia,2011,NaN,8.32,213.56,0.0,27.33,11.345427,69714.1900,5.23,386380.004900,2.469746,62574.145700,3,7741220.0
180,Australia,2012,NaN,8.29,206.75,0.0,26.63,11.410575,67583.0300,4.98,386970.001200,3.917362,68027.841710,3,7741220.0
181,Australia,2013,NaN,9.21,195.78,0.0,34.20,14.870858,67307.0400,4.93,380279.998800,2.600212,68156.627920,3,7741220.0
182,Australia,2014,NaN,9.32,205.46,0.0,36.15,14.962130,66744.1950,4.78,371630.004900,2.562932,62511.690590,3,7741220.0
183,Australia,2015,NaN,9.31,197.72,0.0,33.12,14.347600,67234.9300,4.67,377799.987800,2.172205,56707.022080,3,7741220.0
184,Australia,2016,NaN,9.42,207.66,0.0,38.41,15.609379,66407.0900,4.54,384989.990200,2.741643,49881.763710,3,7741220.0
185,Australia,2017,NaN,9.69,209.14,0.0,40.77,16.313873,65146.3160,4.49,389160.003700,2.295927,53934.250180,3,7741220.0
186,Australia,2018,NaN,9.67,207.45,0.0,42.93,17.145937,65072.6680,4.39,387070.007300,2.870972,57180.779400,3,7741220.0
187,Australia,2019,NaN,10.13,196.45,0.0,53.41,21.375970,66263.5400,4.30,386529.998800,2.113149,54875.285960,3,7741220.0
188,Australia,2020,NaN,NaN,186.92,0.0,63.99,25.503168,61826.2100,NaN,NaN,-0.003837,51692.842750,3,7741220.0
189,Austria,2000,NaN,26.44,16.41,0.0,43.44,72.581460,48863.2800,3.22,63530.000000,3.375722,24564.458290,109,83871.0
190,Austria,2001,NaN,25.53,18.82,0.0,42.24,69.177860,50421.1050,3.36,67910.000000,1.267168,24537.514260,109,83871.0
191,Austria,2002,NaN,24.68,18.79,0.0,41.90,69.039380,50254.6400,3.33,69370.002750,1.651554,26401.745460,109,83871.0
192,Austria,2003,NaN,22.56,22.82,0.0,35.24,60.695835,50523.2030,3.48,74459.999080,0.941471,32222.897240,109,83871.0
193,Austria,2004,NaN,23.17,22.31,0.0,39.62,63.975456,51139.3120,3.44,75800.003050,2.735120,36821.521470,109,83871.0
194,Austria,2005,NaN,24.41,23.61,0.0,40.88,63.389675,51714.7200,3.47,76239.997860,2.244065,38403.133880,109,83871.0
195,Austria,2006,NaN,26.64,21.62,0.0,40.66,65.285805,50921.6840,3.38,74099.998470,3.454042,40635.281820,109,83871.0
196,Austria,2007,NaN,28.99,19.74,0.0,43.17,68.621840,49669.1950,3.20,71239.997860,3.727415,46855.771750,109,83871.0
197,Austria,2008,NaN,29.68,19.97,0.0,44.53,69.038760,50475.0080,3.18,70730.003360,1.460424,51708.765750,109,83871.0
198,Austria,2009,NaN,31.31,19.12,0.0,47.18,71.161385,48765.1840,3.14,64419.998170,-3.764578,47963.179400,109,83871.0
199,Austria,2010,NaN,31.15,22.92,0.0,44.99,66.249440,50240.9600,3.29,69959.999080,1.837094,46858.043270,109,83871.0
200,Austria,2011,NaN,31.64,21.35,0.0,40.91,65.708320,47200.4840,3.10,68269.996640,2.922797,51374.958410,109,83871.0
201,Austria,2012,NaN,34.38,17.37,0.0,51.33,74.716160,49174.5940,3.07,65110.000610,0.680446,48567.695290,109,83871.0
202,Austria,2013,NaN,34.59,14.09,0.0,50.50,78.185486,48493.5740,3.10,65750.000000,0.025505,50716.708710,109,83871.0
203,Austria,2014,NaN,35.67,11.42,0.0,50.20,81.467060,46196.4650,2.97,62049.999240,0.661273,51717.495940,109,83871.0
204,Austria,2015,NaN,34.82,14.26,0.0,47.59,76.944220,45686.7850,3.01,63240.001680,1.014502,44178.047380,109,83871.0
205,Austria,2016,NaN,34.64,14.17,0.0,51.08,78.283520,46698.7850,2.98,63680.000310,1.989437,45276.831440,109,83871.0
206,Austria,2017,NaN,33.98,16.37,0.0,51.05,75.719376,47423.0470,2.97,65860.000610,2.258572,47312.006230,109,83871.0

In [9]:
df['renewable_electricity_generating_capacity_per_capita'] = df['renewable_electricity_generating_capacity_per_capita'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [10]:
df.isna().sum()

country                                                               0
year                                                                  0
renewable_electricity_generating_capacity_per_capita                  0
renewable_energy_share_in_the_total_final_energy_consumption_(%)    194
electricity_from_fossil_fuels_(twh)                                  21
electricity_from_nuclear_(twh)                                      126
electricity_from_renewables_(twh)                                    21
low_carbon_electricity_(%_electricity)                               42
primary_energy_consumption_per_capita_(kwh/person)                    0
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         207
value_co2_emissions_kt_by_country                                   428
gdp_growth                                                          317
gdp_per_capita                                                      282
density\n(p/km2)                                                      1
land_area(km2)                                                        1
dtype: int64

In [11]:
df['renewable_energy_share_in_the_total_final_energy_consumption_(%)'].tail(60)

3589     0.78
3590     0.75
3591     0.74
3592     0.76
3593     0.76
3594     0.74
3595     0.70
3596     0.78
3597     0.93
3598     1.08
3599     0.76
3600     0.76
3601     1.96
3602     2.48
3603     2.80
3604     3.60
3605     3.11
3606      NaN
3607    89.98
3608    89.76
3609    89.56
3610    89.20
3611    89.28
3612    88.68
3613    89.43
3614    90.32
3615    89.36
3616    88.68
3617    88.59
3618    87.28
3619    84.63
3620    84.56
3621    83.77
3622    83.09
3623    83.07
3624    81.89
3625    82.28
3626    84.50
3627      NaN
3628    69.26
3629    71.53
3630    74.30
3631    77.83
3632    81.58
3633    80.15
3634    78.59
3635    77.97
3636    81.86
3637    82.09
3638    82.27
3639    79.27
3640    77.50
3641    78.87
3642    80.27
3643    80.82
3644    81.90
3645    82.46
3646    80.23
3647    81.50
3648    81.90
Name: renewable_energy_share_in_the_total_final_energy_consumption_(%), dtype: float64

In [12]:
df['renewable_energy_share_in_the_total_final_energy_consumption_(%)'] = df['renewable_energy_share_in_the_total_final_energy_consumption_(%)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [13]:
df['renewable_energy_share_in_the_total_final_energy_consumption_(%)'].isna().sum()

0

In [14]:
df.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
5,Afghanistan,2005,7.51,33.88,0.34,0.0,0.59,63.440857,252.06912,1.41,1549.999952,11.229715,242.031313,60,652230.0
6,Afghanistan,2006,7.40,31.89,0.20,0.0,0.64,76.190475,304.42090,1.50,1759.999990,5.357403,263.733602,60,652230.0
7,Afghanistan,2007,7.25,28.78,0.20,0.0,0.75,78.947370,354.27990,1.53,1769.999981,13.826320,359.693158,60,652230.0
8,Afghanistan,2008,7.49,21.17,0.19,0.0,0.54,73.972600,607.83350,1.94,3559.999943,3.924984,364.663542,60,652230.0
9,Afghanistan,2009,7.50,16.53,0.16,0.0,0.78,82.978720,975.04816,2.25,4880.000114,21.390528,437.268740,60,652230.0
10,Afghanistan,2010,8.27,15.15,0.19,0.0,0.75,79.787230,1182.89200,2.46,7110.000134,14.362441,543.306526,60,652230.0
11,Afghanistan,2011,8.13,12.61,0.18,0.0,0.60,76.923090,1436.11430,3.23,8930.000305,0.426355,591.190030,60,652230.0
12,Afghanistan,2012,9.29,15.36,0.14,0.0,0.74,84.090910,1324.12110,2.61,8079.999924,12.752287,638.845852,60,652230.0
13,Afghanistan,2013,9.10,16.86,0.22,0.0,0.89,80.180176,1060.79260,2.46,5989.999771,5.600745,624.315454,60,652230.0
14,Afghanistan,2014,8.95,18.93,0.16,0.0,1.00,86.206900,868.57620,2.25,4880.000114,2.724543,614.223342,60,652230.0
15,Afghanistan,2015,8.79,17.53,0.15,0.0,1.03,87.288140,970.08030,2.37,5949.999809,1.451315,556.007221,60,652230.0
16,Afghanistan,2016,9.87,19.92,0.15,0.0,1.06,87.603294,862.79114,2.24,5300.000191,2.260314,512.012778,60,652230.0
17,Afghanistan,2017,9.79,19.21,0.18,0.0,1.09,85.826775,829.31195,2.30,4780.000210,2.647003,516.679862,60,652230.0
18,Afghanistan,2018,9.55,17.96,0.20,0.0,0.97,82.905980,924.25085,2.44,6070.000172,1.189228,485.668419,60,652230.0
19,Afghanistan,2019,9.58,18.51,0.18,0.0,0.89,83.177570,802.61255,2.41,6079.999924,3.911603,494.179350,60,652230.0
20,Afghanistan,2020,9.35,0.00,0.12,0.0,0.68,85.000000,702.88800,NaN,NaN,-2.351101,516.747871,60,652230.0
21,Albania,2000,0.00,0.00,0.14,0.0,4.55,97.014930,9029.43750,4.13,3170.000000,6.946217,1126.683340,105,28748.0
22,Albania,2001,0.00,0.00,0.13,0.0,3.52,96.438354,8635.53200,3.89,3230.000000,8.293313,1281.659826,105,28748.0
23,Albania,2002,0.00,0.00,0.16,0.0,3.48,95.604390,9443.55500,4.10,3759.999990,4.536524,1425.124219,105,28748.0
24,Albania,2003,0.00,0.00,0.10,0.0,5.12,98.084300,10756.61200,3.80,4070.000172,5.528637,1846.120121,105,28748.0
25,Albania,2004,0.00,0.00,0.13,0.0,5.41,97.653430,11586.95100,3.96,4250.000000,5.514668,2373.581292,105,28748.0
26,Albania,2005,0.00,0.00,0.07,0.0,5.32,98.701300,11545.61600,3.75,4030.000210,5.526424,2673.786584,105,28748.0
27,Albania,2006,0.00,0.00,0.09,0.0,4.95,98.214280,10976.72800,3.46,4010.000229,5.902659,2972.742924,105,28748.0
28,Albania,2007,0.00,0.00,0.07,0.0,2.76,97.526505,9534.87400,3.12,4139.999866,5.983260,3595.038057,105,28748.0
29,Albania,2008,0.00,0.00,0.07,0.0,3.76,98.172325,10499.32800,3.01,4079.999924,7.500041,4370.539925,105,28748.0
30,Albania,2009,0.00,0.00,0.00,0.0,5.20,100.000000,11524.42800,2.98,4219.999790,3.354289,4114.134899,105,28748.0
31,Albania,2010,0.00,0.00,0.00,0.0,7.49,100.000000,12377.50400,2.85,4449.999809,3.706938,4094.348386,105,28748.0
32,Albania,2011,0.00,0.00,0.06,0.0,4.09,98.554214,10854.64900,2.91,4849.999905,2.545406,4437.142612,105,28748.0
33,Albania,2012,0.00,0.00,0.00,0.0,4.68,100.000000,10652.80900,2.57,4360.000134,1.417243,4247.630047,105,28748.0
34,Albania,2013,0.00,0.00,0.00,0.0,6.89,100.000000,13392.77400,2.96,4440.000057,1.002018,4413.062005,105,28748.0
35,Albania,2014,0.00,0.00,0.00,0.0,4.68,100.000000,11809.46100,2.93,4820.000172,1.774449,4578.633208,105,28748.0
36,Albania,2015,0.00,0.00,0.00,0.0,5.84,100.000000,11824.31400,2.69,4619.999886,2.218726,3952.802538,105,28748.0
37,Albania,2016,0.00,0.00,0.00,0.0,7.70,100.000000,13823.74800,2.68,4480.000019,3.314981,4124.055390,105,28748.0
38,Albania,2017,0.00,0.00,0.00,0.0,4.48,100.000000,12802.36000,2.69,5139.999866,3.802227,4531.019374,105,28748.0
39,Albania,2018,0.00,0.00,0.00,0.0,8.47,100.000000,14609.70100,2.57,5110.000134,4.019360,5287.663694,105,28748.0
40,Albania,2019,0.00,0.00,0.00,0.0,5.17,100.000000,11585.55500,2.50,4829.999924,2.113420,5395.659532,105,28748.0
41,Albania,2020,0.00,0.00,0.00,0.0,5.31,100.000000,11158.00300,NaN,NaN,-3.955398,5246.292306,105,28748.0
42,Algeria,2000,8.91,0.43,23.84,0.0,0.05,0.209293,9746.52400,4.18,80050.000000,3.800000,1765.027146,18,2381741.0
43,Algeria,2001,8.79,0.43,24.96,0.0,0.07,0.279664,9961.64000,4.07,78650.000000,3.000000,1740.606654,18,2381741.0
44,Algeria,2002,8.68,0.51,25.94,0.0,0.06,0.230769,10180.35000,4.12,82400.001530,5.600000,1781.828908,18,2381741.0
45,Algeria,2003,8.57,0.47,27.54,0.0,0.26,0.935252,10510.46100,4.08,88190.002440,7.200000,2103.381291,18,2381741.0
46,Algeria,2004,8.46,0.44,29.14,0.0,0.25,0.850630,10759.02200,3.96,89489.997860,4.300000,2610.185422,18,2381741.0
47,Algeria,2005,8.34,0.58,31.36,0.0,0.55,1.723598,11113.72300,3.90,94190.002440,5.900000,3113.094883,18,2381741.0
48,Algeria,2006,7.42,0.41,32.90,0.0,0.22,0.664251,11341.98000,4.10,99809.997560,1.700000,3478.710002,18,2381741.0
49,Algeria,2007,7.30,0.41,34.75,0.0,0.22,0.629111,11759.70100,4.21,102750.000000,3.400000,3950.512993,18,2381741.0
50,Algeria,2008,6.64,0.30,37.55,0.0,0.28,0.740153,12252.29700,4.16,107750.000000,2.400000,4923.631615,18,2381741.0
51,Algeria,2009,6.44,0.31,35.91,0.0,0.30,0.828500,12753.12000,4.48,112169.998200,1.600000,3883.270900,18,2381741.0
52,Algeria,2010,7.02,0.26,42.82,0.0,0.17,0.395441,12243.15600,4.42,114180.000300,3.600000,4480.786318,18,2381741.0
53,Algeria,2011,6.89,0.18,47.67,0.0,0.50,1.037991,12710.54100,4.47,120790.000900,2.900000,5455.679403,18,2381741.0
54,Algeria,2012,6.76,0.18,53.36,0.0,0.62,1.148573,13624.90900,4.72,134929.992700,3.400000,5592.220115,18,2381741.0
55,Algeria,2013,6.62,0.13,55.99,0.0,0.33,0.585938,14130.73500,4.76,139020.004300,2.800000,5499.587331,18,2381741.0
56,Algeria,2014,6.78,0.07,60.15,0.0,0.25,0.413907,15108.63500,5.00,147740.005500,3.800000,5493.056695,18,2381741.0
57,Algeria,2015,7.85,0.06,64.46,0.0,0.22,0.340136,15616.31100,5.05,156270.004300,3.700000,4177.889542,18,2381741.0
58,Algeria,2016,11.88,0.08,66.43,0.0,0.34,0.509211,15295.14300,4.85,154910.003700,3.200000,3946.452447,18,2381741.0
59,Algeria,2017,16.02,0.14,70.86,0.0,0.64,0.895105,15164.00000,4.93,158339.996300,1.300000,4109.698217,18,2381741.0

In [15]:
valores_nulos = df[df['electricity_from_fossil_fuels_(twh)'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
3397,Tuvalu,2000,0.64,0.00,NaN,NaN,NaN,NaN,0.0,3.46,10.0,-0.970600,1463.166211,393,26.0
3398,Tuvalu,2001,0.63,0.00,NaN,NaN,NaN,NaN,0.0,4.19,10.0,1.634108,1392.334348,393,26.0
3399,Tuvalu,2002,0.62,0.00,NaN,NaN,NaN,NaN,0.0,3.64,10.0,7.886174,1610.653001,393,26.0
3400,Tuvalu,2003,0.62,0.00,NaN,NaN,NaN,NaN,0.0,3.51,10.0,-3.333537,1874.853819,393,26.0
3401,Tuvalu,2004,0.61,0.00,NaN,NaN,NaN,NaN,0.0,3.44,10.0,-1.352181,2181.636269,393,26.0
3402,Tuvalu,2005,0.60,0.00,NaN,NaN,NaN,NaN,0.0,3.57,10.0,-3.779730,2184.565259,393,26.0
3403,Tuvalu,2006,0.59,0.00,NaN,NaN,NaN,NaN,0.0,4.67,10.0,2.138938,2263.575948,393,26.0
3404,Tuvalu,2007,0.59,0.00,NaN,NaN,NaN,NaN,0.0,5.23,10.0,6.350565,2645.109505,393,26.0
3405,Tuvalu,2008,2.52,0.00,NaN,NaN,NaN,NaN,0.0,3.50,10.0,7.983261,2936.521547,393,26.0
3406,Tuvalu,2009,20.07,0.00,NaN,NaN,NaN,NaN,0.0,4.13,10.0,-4.432851,2602.619444,393,26.0
3407,Tuvalu,2010,19.86,0.26,NaN,NaN,NaN,NaN,0.0,3.88,10.0,-2.729428,3024.761774,393,26.0
3408,Tuvalu,2011,19.95,0.26,NaN,NaN,NaN,NaN,0.0,3.84,10.0,7.515954,3643.121608,393,26.0
3409,Tuvalu,2012,19.73,0.31,NaN,NaN,NaN,NaN,0.0,3.75,10.0,-3.835749,3506.308144,393,26.0
3410,Tuvalu,2013,19.54,0.83,NaN,NaN,NaN,NaN,0.0,3.26,10.0,4.576824,3457.376266,393,26.0
3411,Tuvalu,2014,25.33,0.80,NaN,NaN,NaN,NaN,0.0,3.10,10.0,1.348013,3398.396750,393,26.0
3412,Tuvalu,2015,185.96,3.88,NaN,NaN,NaN,NaN,0.0,2.64,10.0,9.142894,3197.772252,393,26.0
3413,Tuvalu,2016,197.83,9.46,NaN,NaN,NaN,NaN,0.0,2.56,10.0,3.034723,3253.899536,393,26.0
3414,Tuvalu,2017,195.95,8.74,NaN,NaN,NaN,NaN,0.0,2.55,10.0,4.094018,3574.065288,393,26.0
3415,Tuvalu,2018,194.52,8.32,NaN,NaN,NaN,NaN,0.0,2.86,10.0,2.500000,3701.709255,393,26.0
3416,Tuvalu,2019,192.02,8.20,NaN,NaN,NaN,NaN,0.0,2.61,10.0,9.756098,4055.895610,393,26.0
3417,Tuvalu,2020,196.07,0.00,NaN,NaN,NaN,NaN,0.0,NaN,NaN,4.400000,4143.109753,393,26.0

In [16]:
df['electricity_from_fossil_fuels_(twh)'] = df['electricity_from_fossil_fuels_(twh)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [17]:
df['electricity_from_renewables_(twh)'] = df['electricity_from_renewables_(twh)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [18]:
valores_nulos = df[df['electricity_from_nuclear_(twh)'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
693,Chile,2000,290.18,31.36,20.42,NaN,18.48,47.506424,20023.1350,4.39,50420.00000,5.326938,5074.902616,26,756096.0
694,Chile,2001,286.86,32.15,19.59,NaN,21.03,51.772526,20184.5800,4.17,48430.00000,3.303047,4574.594716,26,756096.0
695,Chile,2002,285.57,33.07,19.87,NaN,22.50,53.103610,20441.2850,4.19,49119.99893,3.106971,4446.249371,26,756096.0
696,Chile,2003,283.29,31.62,23.30,NaN,21.84,48.382810,20334.6620,4.07,50200.00076,4.091048,4772.563723,26,756096.0
697,Chile,2004,327.57,31.44,27.79,NaN,20.87,42.889440,21494.5530,4.04,54970.00122,7.209540,6194.852720,26,756096.0
698,Chile,2005,325.16,32.26,25.20,NaN,25.42,50.217308,22090.8790,3.94,55970.00122,5.742830,7598.528877,26,756096.0
699,Chile,2006,322.11,32.91,25.54,NaN,28.03,52.324062,22631.8930,3.86,57150.00153,6.317176,9464.548507,26,756096.0
700,Chile,2007,327.89,30.46,33.69,NaN,22.29,39.817790,22387.7800,3.81,64569.99969,4.905325,10502.350710,26,756096.0
701,Chile,2008,331.26,30.83,32.59,NaN,23.78,42.185562,22165.2600,3.65,67989.99786,3.529531,10751.481600,26,756096.0
702,Chile,2009,361.58,31.53,32.12,NaN,24.57,43.340977,21051.6780,3.61,65449.99695,-1.564239,10208.907970,26,756096.0
703,Chile,2010,360.95,27.04,36.71,NaN,21.55,36.989360,21403.4400,3.56,69750.00000,5.844177,12808.038340,26,756096.0
704,Chile,2011,388.65,28.79,41.00,NaN,21.04,33.913605,22459.6200,3.66,76470.00122,6.110919,14637.233440,26,756096.0
705,Chile,2012,405.49,30.31,45.17,NaN,20.59,31.310825,23224.0740,3.84,78410.00366,5.318628,15351.540740,26,756096.0
706,Chile,2013,436.94,30.23,48.00,NaN,20.17,29.587795,23629.9860,3.82,83000.00000,4.045004,15842.936480,26,756096.0
707,Chile,2014,468.99,26.95,44.51,NaN,25.44,36.368835,23154.3750,3.39,76559.99756,1.766740,14670.988910,26,756096.0
708,Chile,2015,470.34,25.07,44.37,NaN,27.38,38.160280,23180.0210,3.39,82230.00336,2.303767,13574.169240,26,756096.0
709,Chile,2016,510.67,24.55,49.09,NaN,24.27,33.083424,23993.9300,3.54,86489.99786,1.711089,13753.592150,26,756096.0
710,Chile,2017,557.03,24.11,44.90,NaN,29.32,39.504177,24517.2380,3.55,87069.99969,1.184545,14998.817060,26,756096.0
711,Chile,2018,584.92,25.46,43.85,NaN,32.89,42.859005,25039.6400,3.49,86610.00061,3.713859,15888.144360,26,756096.0
712,Chile,2019,606.69,25.26,45.16,NaN,32.23,41.646210,24894.5140,3.66,91370.00275,0.942005,14741.714400,26,756096.0
713,Chile,2020,669.29,0.00,43.69,NaN,34.06,43.807076,22925.9260,NaN,NaN,-5.771502,13231.704210,26,756096.0
1555,Indonesia,2000,25.89,45.62,78.43,NaN,19.60,19.993880,5435.4355,5.42,280650.00000,4.920068,780.190205,151,1904569.0
1556,Indonesia,2001,21.71,44.33,83.96,NaN,22.19,20.904380,5740.4346,5.34,302060.00000,3.643466,748.257609,151,1904569.0
1557,Indonesia,2002,21.61,44.66,92.03,NaN,21.00,18.579138,5815.3860,5.30,305640.01460,4.499475,900.177588,151,1904569.0
1558,Indonesia,2003,21.48,43.00,97.57,NaN,19.82,16.883892,6224.9414,5.07,333890.01460,4.780369,1065.648520,151,1904569.0
1559,Indonesia,2004,21.40,41.46,103.80,NaN,20.97,16.806925,6087.6787,5.14,341239.99020,5.030874,1150.261367,151,1904569.0
1560,Indonesia,2005,23.61,41.57,110.22,NaN,22.66,17.052980,6186.4365,4.94,342149.99390,5.692571,1263.287332,151,1904569.0
1561,Indonesia,2006,24.78,40.07,116.80,NaN,21.18,15.350051,6211.2920,4.79,364470.00120,5.500952,1589.801489,151,1904569.0
1562,Indonesia,2007,24.93,40.01,124.10,NaN,24.29,16.369028,6579.2300,4.48,379959.99150,6.345022,1860.002811,151,1904569.0
1563,Indonesia,2008,24.94,41.12,129.55,NaN,26.34,16.896530,6569.1010,4.30,376140.01460,6.013704,2166.854231,151,1904569.0
1564,Indonesia,2009,28.08,38.18,136.05,NaN,26.79,16.451733,6662.8240,4.34,391079.98660,4.628871,2261.247309,151,1904569.0
1565,Indonesia,2010,28.35,34.81,142.88,NaN,34.63,19.508760,7121.8190,4.21,415519.98900,6.223854,3122.362673,151,1904569.0
1566,Indonesia,2011,29.16,30.92,161.41,NaN,30.46,15.875333,7429.8623,4.04,475309.99760,6.169784,3643.047176,151,1904569.0
1567,Indonesia,2012,30.14,28.78,177.83,NaN,31.11,14.889442,7574.4570,3.79,481510.00980,6.030051,3694.359340,151,1904569.0
1568,Indonesia,2013,32.81,29.70,189.66,NaN,35.50,15.766565,7225.1826,3.47,447940.00240,5.557264,3623.927241,151,1904569.0
1569,Indonesia,2014,32.99,28.32,203.11,NaN,34.41,14.487201,7235.5580,3.44,483910.00370,5.006668,3491.637491,151,1904569.0
1570,Indonesia,2015,33.18,26.69,209.71,NaN,33.56,13.795372,7266.8945,3.26,488549.98780,4.876322,3331.695115,151,1904569.0
1571,Indonesia,2016,34.65,28.24,217.97,NaN,39.58,15.367891,7212.0700,3.19,482510.00980,5.033069,3562.816334,151,1904569.0
1572,Indonesia,2017,35.74,26.15,222.64,NaN,43.17,16.240925,7388.5230,3.20,517320.00730,5.069786,3837.578024,151,1904569.0
1573,Indonesia,2018,36.64,21.05,235.41,NaN,48.38,17.047817,8026.8910,3.19,576989.99020,5.174292,3893.859578,151,1904569.0
1574,Indonesia,2019,38.06,19.09,247.39,NaN,48.04,16.261044,8474.4795,3.16,619840.02690,5.018160,4135.201531,151,1904569.0
1575,Indonesia,2020,38.58,0.00,238.91,NaN,52.91,18.131039,7771.0420,NaN,NaN,-2.069543,3869.588427,151,1904569.0
1723,Kazakhstan,2000,151.45,2.50,44.11,NaN,7.53,14.581719,24267.6020,9.77,120150.00000,9.800000,1229.001247,7,2724900.0
1724,Kazakhstan,2001,151.57,2.41,47.30,NaN,8.08,14.590104,27235.3790,8.33,117440.00000,13.500000,1490.927090,7,2724900.0
1725,Kazakhstan,2002,150.91,2.77,49.44,NaN,8.89,15.240871,27638.3520,8.73,131059.99760,9.800000,1658.030785,7,2724900.0
1726,Kazakhstan,2003,149.67,2.28,55.24,NaN,8.62,13.498278,30142.0200,8.66,146139.99940,9.300000,2068.123979,7,2724900.0
1727,Kazakhstan,2004,148.39,1.89,58.89,NaN,8.06,12.038837,31813.2400,9.31,158029.99880,9.600000,2874.288483,7,2724900.0
1728,Kazakhstan,2005,146.02,2.09,60.06,NaN,7.86,11.572438,32415.7340,8.51,169210.00670,9.700000,3771.278957,7,2724900.0
1729,Kazakhstan,2006,144.76,2.13,63.89,NaN,7.77,10.842869,34517.4960,9.15,185300.00310,10.700000,5291.575305,7,2724900.0
1730,Kazakhstan,2007,143.40,1.83,68.45,NaN,8.17,10.663012,37807.3000,9.16,198389.99940,8.900000,6771.414797,7,2724900.0
1731,Kazakhstan,2008,142.74,1.15,72.89,NaN,7.46,9.284381,39400.2270,9.38,242029.99880,3.300000,8458.017154,7,2724900.0
1732,Kazakhstan,2009,141.26,1.31,71.85,NaN,6.88,8.738727,34913.5000,8.42,213610.00060,1.200000,7165.223175,7,2724900.0
1733,Kazakhstan,2010,140.02,1.38,74.63,NaN,8.02,9.703569,36949.3320,8.55,229699.99690,7.300000,9070.488253,7,2724900.0
1734,Kazakhstan,2011,138.11,1.38,78.70,NaN,7.88,9.101409,41342.9900,8.90,245449.99690,7.400000,11634.001200,7,2724900.0
1735,Kazakhstan,2012,154.11,1.33,82.98,NaN,7.64,8.430810,42868.2300,8.12,244600.00610,4.800000,12386.699270,7,2724900.0
1736,Kazakhstan,2013,153.18,1.16,84.88,NaN,7.73,8.346830,42457.9100,8.45,260010.00980,6.000000,13890.630960,7,2724900.0
1737,Kazakhstan,2014,162.11,1.34,86.37,NaN,8.27,8.738378,43947.9730,6.48,209229.99570,4.200000,12807.260690,7,2724900.0
1738,Kazakhstan,2015,164.65,1.72,82.20,NaN,9.45,10.310966,36005.6400,5.38,190729.99570,1.200000,10510.771890,7,2724900.0
1739,Kazakhstan,2016,165.50,2.07,82.65,NaN,11.98,12.659833,39906.7800,6.22,202149.99390,1.100000,7714.841844,7,2724900.0
1740,Kazakhstan,2017,166.77,2.02,91.48,NaN,11.64,11.287820,42406.9900,6.08,214580.00180,4.100000,9247.581331,7,2724900.0

In [19]:
valores_nulos.tail(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
2020,Malaysia,2003,113.41,3.33,77.25,NaN,5.51,6.657805,28867.148,5.63,144490.0055,5.788499,4461.847325,99,329847.0
2021,Malaysia,2004,111.19,3.22,89.30,NaN,6.15,6.443164,30459.574,5.68,158270.0043,6.783438,4952.213958,99,329847.0
2022,Malaysia,2005,107.28,3.01,91.79,NaN,6.60,6.707999,32213.139,5.85,167419.9982,5.332139,5587.024780,99,329847.0
2023,Malaysia,2006,106.98,3.13,96.31,NaN,6.94,6.721550,31831.441,5.57,174100.0061,5.584847,6209.126167,99,329847.0
2024,Malaysia,2007,105.86,2.85,101.52,NaN,6.72,6.208426,33221.490,5.59,189940.0024,6.298786,7243.456801,99,329847.0
2025,Malaysia,2008,104.09,3.04,105.01,NaN,8.61,7.577890,33712.133,5.65,202910.0037,4.831770,8474.587762,99,329847.0
2026,Malaysia,2009,102.42,2.27,107.66,NaN,8.28,7.141625,32003.473,5.42,181929.9927,-1.513529,7292.494973,99,329847.0
2027,Malaysia,2010,99.15,1.96,117.16,NaN,7.62,6.106748,32487.746,5.24,200220.0012,7.424847,9040.568495,99,329847.0
2028,Malaysia,2011,135.95,2.16,117.43,NaN,9.60,7.557270,32524.594,5.19,202740.0055,5.293913,10399.370210,99,329847.0
2029,Malaysia,2012,145.91,2.52,123.23,NaN,10.76,8.030450,35010.120,4.99,205809.9976,5.473454,10817.431710,99,329847.0
2030,Malaysia,2013,192.63,2.75,127.86,NaN,13.04,9.254791,36062.543,5.38,223660.0037,4.693723,10970.104300,99,329847.0
2031,Malaysia,2014,212.85,3.03,133.16,NaN,14.31,9.703669,35862.223,5.18,236649.9939,6.006722,11319.061940,99,329847.0
2032,Malaysia,2015,249.45,3.41,135.17,NaN,14.94,9.952702,35878.008,4.72,236539.9933,5.091532,9955.242722,99,329847.0
2033,Malaysia,2016,259.33,4.43,135.56,NaN,21.09,13.463135,37199.580,4.69,235960.0067,4.449781,9817.787090,99,329847.0
2034,Malaysia,2017,235.74,5.22,132.70,NaN,27.94,17.392930,37162.887,4.28,227619.9951,5.812722,10259.304810,99,329847.0
2035,Malaysia,2018,239.17,5.31,142.27,NaN,28.31,16.596320,37333.030,4.50,244410.0037,4.843057,11380.082090,99,329847.0
2036,Malaysia,2019,251.85,5.11,149.70,NaN,28.76,16.115656,37823.500,4.25,253270.0043,4.439471,11432.823000,99,329847.0
2037,Malaysia,2020,268.76,0.00,138.77,NaN,30.54,18.037918,35997.363,NaN,NaN,-5.646945,10412.348980,99,329847.0
2871,Saudi Arabia,2000,0.02,0.01,138.68,NaN,0.00,0.000000,61950.850,4.73,249660.0000,5.625416,9171.331476,16,2149690.0
2872,Saudi Arabia,2001,0.02,0.01,146.09,NaN,0.00,0.000000,64399.926,4.91,254090.0000,-1.210744,8684.645762,16,2149690.0
2873,Saudi Arabia,2002,0.02,0.01,154.91,NaN,0.00,0.000000,65480.074,5.74,272250.0000,-2.819174,8695.396483,16,2149690.0
2874,Saudi Arabia,2003,0.02,0.01,166.58,NaN,0.00,0.000000,67781.130,5.18,284829.9866,11.242061,9609.968686,16,2149690.0
2875,Saudi Arabia,2004,0.01,0.01,173.41,NaN,0.00,0.000000,71949.190,4.83,299890.0146,7.958442,11185.137040,16,2149690.0
2876,Saudi Arabia,2005,0.01,0.01,191.05,NaN,0.00,0.000000,74232.790,4.87,315290.0085,5.573850,13791.454760,16,2149690.0
2877,Saudi Arabia,2006,0.01,0.01,196.31,NaN,0.00,0.000000,74860.330,5.08,335440.0024,2.788402,15384.738360,16,2149690.0
2878,Saudi Arabia,2007,0.01,0.01,204.43,NaN,0.00,0.000000,73638.340,5.24,354619.9951,1.847130,16516.631780,16,2149690.0
2879,Saudi Arabia,2008,0.01,0.01,204.20,NaN,0.00,0.000000,77575.414,5.40,389720.0012,6.249773,20078.260070,16,2149690.0
2880,Saudi Arabia,2009,0.01,0.01,217.31,NaN,0.00,0.000000,77417.270,5.79,406529.9988,-2.059249,16113.143710,16,2149690.0
2881,Saudi Arabia,2010,0.09,0.01,240.06,NaN,0.00,0.000000,83337.160,6.08,446130.0049,5.039484,19262.547600,16,2149690.0
2882,Saudi Arabia,2011,0.10,0.01,250.07,NaN,0.01,0.003999,84816.250,5.79,463769.9890,9.996847,23745.880580,16,2149690.0
2883,Saudi Arabia,2012,0.47,0.01,271.68,NaN,0.03,0.011041,88062.086,5.64,492470.0012,5.411445,25243.602000,16,2149690.0
2884,Saudi Arabia,2013,0.75,0.01,284.02,NaN,0.04,0.014082,86753.600,5.46,503209.9915,2.699255,24845.124660,16,2149690.0
2885,Saudi Arabia,2014,0.79,0.01,311.81,NaN,0.05,0.016033,91258.060,5.81,540520.0195,3.652482,24464.212560,16,2149690.0
2886,Saudi Arabia,2015,0.76,0.01,338.34,NaN,0.05,0.014776,93332.540,5.84,565190.0024,4.106409,20627.926930,16,2149690.0
2887,Saudi Arabia,2016,0.75,0.01,337.38,NaN,0.05,0.014818,95158.550,5.70,561229.9805,1.670625,19878.763840,16,2149690.0
2888,Saudi Arabia,2017,1.12,0.02,354.30,NaN,0.07,0.019753,93054.375,5.85,545070.0073,-0.741503,20802.466310,16,2149690.0
2889,Saudi Arabia,2018,2.59,0.02,334.70,NaN,0.16,0.047781,88573.470,5.58,521260.0098,2.434111,23337.017550,16,2149690.0
2890,Saudi Arabia,2019,12.04,0.03,335.24,NaN,0.21,0.062602,82989.266,5.58,523780.0293,0.331436,23139.797980,16,2149690.0
2891,Saudi Arabia,2020,11.85,0.00,337.82,NaN,0.21,0.062125,80309.990,NaN,NaN,-4.106583,20110.316190,16,2149690.0
3397,Tuvalu,2000,0.64,0.00,0.00,NaN,0.00,NaN,0.000,3.46,10.0000,-0.970600,1463.166211,393,26.0
3398,Tuvalu,2001,0.63,0.00,0.00,NaN,0.00,NaN,0.000,4.19,10.0000,1.634108,1392.334348,393,26.0
3399,Tuvalu,2002,0.62,0.00,0.00,NaN,0.00,NaN,0.000,3.64,10.0000,7.886174,1610.653001,393,26.0
3400,Tuvalu,2003,0.62,0.00,0.00,NaN,0.00,NaN,0.000,3.51,10.0000,-3.333537,1874.853819,393,26.0
3401,Tuvalu,2004,0.61,0.00,0.00,NaN,0.00,NaN,0.000,3.44,10.0000,-1.352181,2181.636269,393,26.0
3402,Tuvalu,2005,0.60,0.00,0.00,NaN,0.00,NaN,0.000,3.57,10.0000,-3.779730,2184.565259,393,26.0
3403,Tuvalu,2006,0.59,0.00,0.00,NaN,0.00,NaN,0.000,4.67,10.0000,2.138938,2263.575948,393,26.0
3404,Tuvalu,2007,0.59,0.00,0.00,NaN,0.00,NaN,0.000,5.23,10.0000,6.350565,2645.109505,393,26.0
3405,Tuvalu,2008,2.52,0.00,0.00,NaN,0.00,NaN,0.000,3.50,10.0000,7.983261,2936.521547,393,26.0
3406,Tuvalu,2009,20.07,0.00,0.00,NaN,0.00,NaN,0.000,4.13,10.0000,-4.432851,2602.619444,393,26.0
3407,Tuvalu,2010,19.86,0.26,0.00,NaN,0.00,NaN,0.000,3.88,10.0000,-2.729428,3024.761774,393,26.0
3408,Tuvalu,2011,19.95,0.26,0.00,NaN,0.00,NaN,0.000,3.84,10.0000,7.515954,3643.121608,393,26.0
3409,Tuvalu,2012,19.73,0.31,0.00,NaN,0.00,NaN,0.000,3.75,10.0000,-3.835749,3506.308144,393,26.0
3410,Tuvalu,2013,19.54,0.83,0.00,NaN,0.00,NaN,0.000,3.26,10.0000,4.576824,3457.376266,393,26.0
3411,Tuvalu,2014,25.33,0.80,0.00,NaN,0.00,NaN,0.000,3.10,10.0000,1.348013,3398.396750,393,26.0
3412,Tuvalu,2015,185.96,3.88,0.00,NaN,0.00,NaN,0.000,2.64,10.0000,9.142894,3197.772252,393,26.0
3413,Tuvalu,2016,197.83,9.46,0.00,NaN,0.00,NaN,0.000,2.56,10.0000,3.034723,3253.899536,393,26.0
3414,Tuvalu,2017,195.95,8.74,0.00,NaN,0.00,NaN,0.000,2.55,10.0000,4.094018,3574.065288,393,26.0
3415,Tuvalu,2018,194.52,8.32,0.00,NaN,0.00,NaN,0.000,2.86,10.0000,2.500000,3701.709255,393,26.0
3416,Tuvalu,2019,192.02,8.20,0.00,NaN,0.00,NaN,0.000,2.61,10.0000,9.756098,4055.895610,393,26.0
3417,Tuvalu,2020,196.07,0.00,0.00,NaN,0.00,NaN,0.000,NaN,NaN,4.400000,4143.109753,393,26.0

In [20]:
inicio_rango = 3397
fin_rango = 3417

# Utiliza la indexaciÃ³n de rangos para seleccionar las filas y rellenar los nulos con 0
df.loc[inicio_rango:fin_rango, 'electricity_from_nuclear_(twh)'] = df.loc[inicio_rango:fin_rango, 'electricity_from_nuclear_(twh)'].fillna(0)

In [21]:
df['electricity_from_nuclear_(twh)'] = df['electricity_from_nuclear_(twh)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [22]:
df['electricity_from_nuclear_(twh)'].value_counts()

electricity_from_nuclear_(twh)
0.00      3071
5.55         3
11.62        3
3.91         3
43.52        2
          ...
436.76       1
421.08       1
415.16       1
23.29        1
789.88       1
Name: count, Length: 547, dtype: int64

In [23]:
df.tail(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
3589,Yemen,2003,0.00,0.78,3.85,0.0,0.00,0.000000,3707.2222,3.010832,NaN,NaN,NaN,56,527968.0
3590,Yemen,2004,0.00,0.75,4.10,0.0,0.00,0.000000,3811.3972,3.160727,NaN,NaN,NaN,56,527968.0
3591,Yemen,2005,0.00,0.74,4.48,0.0,0.00,0.000000,3906.3083,3.188304,NaN,NaN,NaN,56,527968.0
3592,Yemen,2006,0.00,0.76,5.06,0.0,0.00,0.000000,3788.2456,3.308474,NaN,NaN,NaN,56,527968.0
3593,Yemen,2007,0.00,0.76,5.67,0.0,0.00,0.000000,3902.2861,3.133247,NaN,NaN,NaN,56,527968.0
3594,Yemen,2008,0.04,0.74,6.15,0.0,0.00,0.000000,3976.8901,3.176676,NaN,NaN,NaN,56,527968.0
3595,Yemen,2009,0.04,0.70,6.34,0.0,0.00,0.000000,4277.2236,3.380211,NaN,NaN,NaN,56,527968.0
3596,Yemen,2010,0.04,0.78,7.29,0.0,0.00,0.000000,4030.7585,3.165451,NaN,NaN,NaN,56,527968.0
3597,Yemen,2011,0.05,0.93,5.83,0.0,0.00,0.000000,3289.4512,3.161177,NaN,NaN,NaN,56,527968.0
3598,Yemen,2012,0.06,1.08,6.65,0.0,0.00,0.000000,2769.0400,2.790347,NaN,NaN,NaN,56,527968.0
3599,Yemen,2013,0.09,0.76,7.99,0.0,0.00,0.000000,3797.8290,3.693557,NaN,NaN,NaN,56,527968.0
3600,Yemen,2014,0.19,0.76,7.19,0.0,0.01,0.138889,3495.3290,3.211405,NaN,NaN,NaN,56,527968.0
3601,Yemen,2015,2.26,1.96,5.81,0.0,0.12,2.023609,1837.1029,2.050356,NaN,NaN,NaN,56,527968.0
3602,Yemen,2016,2.94,2.48,4.36,0.0,0.16,3.539823,1432.5522,NaN,NaN,NaN,NaN,56,527968.0
3603,Yemen,2017,3.59,2.80,3.63,0.0,0.19,4.973822,1288.8767,NaN,NaN,NaN,NaN,56,527968.0
3604,Yemen,2018,8.77,3.60,2.82,0.0,0.48,14.545455,1170.7261,NaN,NaN,NaN,NaN,56,527968.0
3605,Yemen,2019,8.57,3.11,2.93,0.0,0.48,14.076246,1475.9852,NaN,NaN,NaN,NaN,56,527968.0
3606,Yemen,2020,8.48,0.00,2.74,0.0,0.49,15.170279,1092.0021,NaN,NaN,NaN,NaN,56,527968.0
3607,Zambia,2000,173.03,89.98,0.07,0.0,7.69,99.097940,2951.3672,12.770000,1810.000000,3.897323,345.689621,25,752618.0
3608,Zambia,2001,168.56,89.76,0.07,0.0,7.83,99.113920,2997.7124,12.490000,1840.000000,5.316868,382.941035,25,752618.0
3609,Zambia,2002,164.26,89.56,0.08,0.0,8.03,99.013565,3006.3240,12.290000,1919.999957,4.506014,382.241963,25,752618.0
3610,Zambia,2003,154.77,89.20,0.08,0.0,8.18,99.031470,3019.9080,11.810000,2079.999924,6.944974,435.458199,25,752618.0
3611,Zambia,2004,150.84,89.28,0.07,0.0,8.39,99.172585,3012.9995,11.290000,2109.999895,7.032395,538.591553,25,752618.0
3612,Zambia,2005,146.95,88.68,0.08,0.0,8.80,99.099100,3068.1736,10.810000,2289.999962,7.235599,702.741118,25,752618.0
3613,Zambia,2006,143.12,89.43,0.08,0.0,9.58,99.171844,3064.4688,10.180000,2180.000067,7.903694,1047.918843,25,752618.0
3614,Zambia,2007,134.61,90.32,0.06,0.0,9.54,99.374990,2793.3340,9.510000,1980.000019,8.352436,1124.290586,25,752618.0
3615,Zambia,2008,133.35,89.36,0.04,0.0,9.45,99.578510,2786.6501,9.060000,2190.000057,7.773896,1394.000500,25,752618.0
3616,Zambia,2009,130.26,88.68,0.05,0.0,9.81,99.492910,2734.8910,8.470000,2490.000010,9.220348,1159.907499,25,752618.0
3617,Zambia,2010,142.25,88.59,0.05,0.0,10.36,99.519690,2768.1340,7.890000,2660.000086,10.298223,1489.459087,25,752618.0
3618,Zambia,2011,138.01,87.28,0.05,0.0,11.40,99.563324,2998.1587,7.850000,3049.999952,5.564602,1672.907535,25,752618.0
3619,Zambia,2012,134.28,84.63,0.06,0.0,12.26,99.512990,3116.7373,7.650000,4030.000210,7.597593,1763.069442,25,752618.0
3620,Zambia,2013,154.25,84.56,0.05,0.0,13.18,99.622080,3198.5288,7.490000,4239.999771,5.057232,1878.346811,25,752618.0
3621,Zambia,2014,149.51,83.77,0.35,0.0,14.01,97.562675,3323.3853,7.450000,4690.000057,4.697992,1762.427817,25,752618.0
3622,Zambia,2015,145.55,83.09,0.36,0.0,13.00,97.305390,3115.0676,7.410000,4960.000038,2.920375,1338.290927,25,752618.0
3623,Zambia,2016,148.58,83.07,0.65,0.0,10.97,94.406200,2846.6990,7.330000,5320.000172,3.776679,1280.806543,25,752618.0
3624,Zambia,2017,144.85,81.89,1.80,0.0,12.64,87.534630,3202.0718,7.440000,6809.999943,3.504336,1535.196574,25,752618.0
3625,Zambia,2018,140.76,82.28,2.24,0.0,13.89,86.112840,3494.5369,7.350000,7730.000019,4.034494,1516.368371,25,752618.0
3626,Zambia,2019,142.11,84.50,2.05,0.0,12.62,86.025900,2983.8816,7.090000,6800.000191,1.441306,1305.001031,25,752618.0
3627,Zambia,2020,138.23,0.00,2.00,0.0,13.10,86.754970,3099.0830,NaN,NaN,-2.785055,985.132436,25,752618.0
3628,Zimbabwe,2000,61.42,69.26,3.30,0.0,3.44,51.038578,4919.5225,9.390000,13700.000000,-3.059190,563.057504,38,390757.0
3629,Zimbabwe,2001,61.20,71.53,4.33,0.0,3.25,42.875988,4614.9575,9.230000,13900.000000,1.439615,568.386290,38,390757.0
3630,Zimbabwe,2002,62.72,74.30,4.12,0.0,4.14,50.121063,4561.2430,9.960000,12489.999770,-8.894024,530.530446,38,390757.0
3631,Zimbabwe,2003,62.58,77.83,2.98,0.0,5.56,65.105385,4397.3420,11.470000,10180.000310,-16.995075,478.007604,38,390757.0
3632,Zimbabwe,2004,62.38,81.58,3.63,0.0,5.78,61.424020,4045.2322,11.900000,9770.000458,-5.807538,482.998451,38,390757.0
3633,Zimbabwe,2005,62.09,80.15,3.84,0.0,5.20,57.522125,4160.4126,13.240000,10510.000230,-5.711084,476.555403,38,390757.0
3634,Zimbabwe,2006,61.68,78.59,2.23,0.0,5.45,70.963550,4158.7817,14.090000,9829.999924,-3.461495,447.854740,38,390757.0
3635,Zimbabwe,2007,61.18,77.97,1.86,0.0,5.49,74.693880,4036.7202,14.400000,9760.000229,-3.653327,431.787259,38,390757.0
3636,Zimbabwe,2008,67.35,81.86,1.60,0.0,5.79,78.349120,3324.8596,16.340000,7599.999905,-17.668946,356.693234,38,390757.0
3637,Zimbabwe,2009,66.60,82.09,1.57,0.0,5.54,77.918430,3254.2820,15.000000,7750.000000,12.019560,771.599032,38,390757.0
3638,Zimbabwe,2010,65.79,82.27,2.49,0.0,5.95,70.497635,3592.6724,12.710000,9600.000381,19.675323,948.331481,38,390757.0
3639,Zimbabwe,2011,66.20,79.27,3.43,0.0,5.51,61.633114,3860.7898,11.770000,11409.999850,14.193913,1093.653409,38,390757.0
3640,Zimbabwe,2012,65.14,77.50,3.25,0.0,5.68,63.605820,4106.9497,10.420000,12010.000230,16.665429,1304.968011,38,390757.0
3641,Zimbabwe,2013,64.44,78.87,3.90,0.0,5.36,57.883370,4085.3320,10.480000,12279.999730,1.989493,1429.998461,38,390757.0
3642,Zimbabwe,2014,63.38,80.27,3.92,0.0,5.79,59.629250,3940.8862,10.400000,12079.999920,2.376929,1434.896277,38,390757.0
3643,Zimbabwe,2015,63.54,80.82,4.02,0.0,5.37,57.188496,3860.9202,10.360000,12430.000310,1.779873,1445.069702,38,390757.0
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.6802,10.000000,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.0115,9.510000,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.9858,9.830000,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.6553,10.470000,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.1318,10.000000,NaN,-6.248748,1214.509820,38,390757.0

In [24]:
valores_nulos = df[df['low_carbon_electricity_(%_electricity)'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
399,Bermuda,2000,0.00,0.46,0.0,0.0,0.0,NaN,39297.880,1.52,517.047,9.317156,56284.168650,1281,54.0
400,Bermuda,2001,0.00,0.54,0.0,0.0,0.0,NaN,39604.938,1.45,528.048,7.222436,58883.959430,1281,54.0
401,Bermuda,2002,0.00,0.51,0.0,0.0,0.0,NaN,41429.880,1.54,557.384,-1.477791,62583.100200,1281,54.0
402,Bermuda,2003,0.00,0.51,0.0,0.0,0.0,NaN,41114.773,1.50,561.051,3.410707,66111.725230,1281,54.0
403,Bermuda,2004,0.00,0.52,0.0,0.0,0.0,NaN,42390.040,1.51,583.053,2.321267,70359.319110,1281,54.0
404,Bermuda,2005,0.00,0.49,0.0,0.0,0.0,NaN,44480.980,1.48,583.053,1.674206,75882.033860,1281,54.0
405,Bermuda,2006,0.00,0.44,0.0,0.0,0.0,NaN,50145.137,1.56,652.726,5.543866,95221.858870,1281,54.0
406,Bermuda,2007,0.00,0.50,0.0,0.0,0.0,NaN,58163.746,1.67,729.733,3.345140,104287.387500,1281,54.0
407,Bermuda,2008,0.00,0.46,0.0,0.0,0.0,NaN,55556.035,1.51,649.059,-1.865956,106935.486300,1281,54.0
408,Bermuda,2009,0.00,0.43,0.0,0.0,0.0,NaN,43647.020,1.21,476.710,-5.626698,101407.764000,1281,54.0
409,Bermuda,2010,0.00,0.43,0.0,0.0,0.0,NaN,51318.156,1.54,608.722,-2.502878,101875.284100,1281,54.0
410,Bermuda,2011,0.00,0.42,0.0,0.0,0.0,NaN,33119.836,1.20,443.707,-3.742744,97774.162070,1281,54.0
411,Bermuda,2012,0.00,0.44,0.0,0.0,0.0,NaN,35803.332,1.08,366.700,-5.305299,98431.865180,1281,54.0
412,Bermuda,2013,0.00,1.47,0.0,0.0,0.0,NaN,35994.320,1.52,509.713,-0.279709,99471.638900,1281,54.0
413,Bermuda,2014,0.00,0.43,0.0,0.0,0.0,NaN,46727.742,1.95,649.059,-3.701068,98467.683990,1281,54.0
414,Bermuda,2015,0.00,0.55,0.0,0.0,0.0,NaN,39425.170,1.59,557.384,0.775530,102005.625600,1281,54.0
415,Bermuda,2016,0.00,1.09,0.0,0.0,0.0,NaN,50238.902,1.83,612.389,-0.657206,106885.878500,1281,54.0
416,Bermuda,2017,0.00,0.64,0.0,0.0,0.0,NaN,49395.460,1.77,NaN,3.611420,111820.581500,1281,54.0
417,Bermuda,2018,0.00,0.67,0.0,0.0,0.0,NaN,50863.380,1.97,NaN,-0.432801,113023.185600,1281,54.0
418,Bermuda,2019,0.00,0.84,0.0,0.0,0.0,NaN,50639.293,1.65,NaN,0.459890,117098.446300,1281,54.0
419,Bermuda,2020,0.00,0.00,0.0,0.0,0.0,NaN,46161.586,NaN,NaN,-6.344080,107079.479800,1281,54.0
3397,Tuvalu,2000,0.64,0.00,0.0,0.0,0.0,NaN,0.000,3.46,10.000,-0.970600,1463.166211,393,26.0
3398,Tuvalu,2001,0.63,0.00,0.0,0.0,0.0,NaN,0.000,4.19,10.000,1.634108,1392.334348,393,26.0
3399,Tuvalu,2002,0.62,0.00,0.0,0.0,0.0,NaN,0.000,3.64,10.000,7.886174,1610.653001,393,26.0
3400,Tuvalu,2003,0.62,0.00,0.0,0.0,0.0,NaN,0.000,3.51,10.000,-3.333537,1874.853819,393,26.0
3401,Tuvalu,2004,0.61,0.00,0.0,0.0,0.0,NaN,0.000,3.44,10.000,-1.352181,2181.636269,393,26.0
3402,Tuvalu,2005,0.60,0.00,0.0,0.0,0.0,NaN,0.000,3.57,10.000,-3.779730,2184.565259,393,26.0
3403,Tuvalu,2006,0.59,0.00,0.0,0.0,0.0,NaN,0.000,4.67,10.000,2.138938,2263.575948,393,26.0
3404,Tuvalu,2007,0.59,0.00,0.0,0.0,0.0,NaN,0.000,5.23,10.000,6.350565,2645.109505,393,26.0
3405,Tuvalu,2008,2.52,0.00,0.0,0.0,0.0,NaN,0.000,3.50,10.000,7.983261,2936.521547,393,26.0
3406,Tuvalu,2009,20.07,0.00,0.0,0.0,0.0,NaN,0.000,4.13,10.000,-4.432851,2602.619444,393,26.0
3407,Tuvalu,2010,19.86,0.26,0.0,0.0,0.0,NaN,0.000,3.88,10.000,-2.729428,3024.761774,393,26.0
3408,Tuvalu,2011,19.95,0.26,0.0,0.0,0.0,NaN,0.000,3.84,10.000,7.515954,3643.121608,393,26.0
3409,Tuvalu,2012,19.73,0.31,0.0,0.0,0.0,NaN,0.000,3.75,10.000,-3.835749,3506.308144,393,26.0
3410,Tuvalu,2013,19.54,0.83,0.0,0.0,0.0,NaN,0.000,3.26,10.000,4.576824,3457.376266,393,26.0
3411,Tuvalu,2014,25.33,0.80,0.0,0.0,0.0,NaN,0.000,3.10,10.000,1.348013,3398.396750,393,26.0
3412,Tuvalu,2015,185.96,3.88,0.0,0.0,0.0,NaN,0.000,2.64,10.000,9.142894,3197.772252,393,26.0
3413,Tuvalu,2016,197.83,9.46,0.0,0.0,0.0,NaN,0.000,2.56,10.000,3.034723,3253.899536,393,26.0
3414,Tuvalu,2017,195.95,8.74,0.0,0.0,0.0,NaN,0.000,2.55,10.000,4.094018,3574.065288,393,26.0
3415,Tuvalu,2018,194.52,8.32,0.0,0.0,0.0,NaN,0.000,2.86,10.000,2.500000,3701.709255,393,26.0
3416,Tuvalu,2019,192.02,8.20,0.0,0.0,0.0,NaN,0.000,2.61,10.000,9.756098,4055.895610,393,26.0
3417,Tuvalu,2020,196.07,0.00,0.0,0.0,0.0,NaN,0.000,NaN,NaN,4.400000,4143.109753,393,26.0

In [25]:
df['low_carbon_electricity_(%_electricity)'] = df['low_carbon_electricity_(%_electricity)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [26]:
valores_nulos = df[df['energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
20,Afghanistan,2020,9.35,0.00,0.12,0.00,0.68,85.000000,702.88800,NaN,NaN,-2.351101,516.747871,60,652230.0
41,Albania,2020,0.00,0.00,0.00,0.00,5.31,100.000000,11158.00300,NaN,NaN,-3.955398,5246.292306,105,28748.0
62,Algeria,2020,15.64,0.00,72.01,0.00,0.72,0.989963,14933.80700,NaN,NaN,-5.100000,3306.858208,18,2381741.0
83,Angola,2020,115.43,0.00,4.49,0.00,12.10,72.935500,3527.16000,NaN,NaN,-5.399987,1776.166868,26,1246700.0
104,Antigua and Barbuda,2020,167.98,0.00,0.31,0.00,0.02,6.060606,27785.22700,NaN,NaN,-20.192371,13992.744480,223,443.0
125,Argentina,2020,311.28,0.00,91.58,10.06,37.05,33.967842,19314.06600,NaN,NaN,-9.895269,8579.017773,17,2780400.0
146,Armenia,2020,484.04,0.00,2.98,2.55,1.92,59.999996,17086.04700,NaN,NaN,-7.400000,4266.018074,104,29743.0
167,Aruba,2020,356.86,0.00,0.73,0.00,0.15,17.045456,43496.94000,NaN,NaN,NaN,NaN,590,179.0
188,Australia,2020,0.00,0.00,186.92,0.00,63.99,25.503168,61826.21000,NaN,NaN,-0.003837,51692.842750,3,7741220.0
209,Austria,2020,0.00,0.00,13.77,0.00,55.42,80.098274,45028.27000,NaN,NaN,-6.734514,48586.801320,109,83871.0
230,Azerbaijan,2020,127.35,0.00,23.16,0.00,1.22,5.004102,17803.62900,NaN,NaN,-4.300000,4221.407478,123,86600.0
251,Bahamas,2020,5.68,0.00,1.99,0.00,0.00,0.000000,33301.77000,NaN,NaN,NaN,NaN,41,13878.0
272,Bahrain,2020,6.13,0.00,29.85,0.00,0.01,0.033490,156095.80000,NaN,NaN,-5.085180,20409.952800,"2,239",765.0
293,Bangladesh,2020,3.12,0.00,74.41,0.00,1.31,1.730058,2730.07800,NaN,NaN,3.509136,1961.613749,"1,265",148460.0
314,Barbados,2020,174.06,0.00,0.93,0.00,0.07,7.000000,21577.82800,NaN,NaN,-18.979510,15373.854700,668,430.0
335,Belarus,2020,0.00,0.00,34.59,0.34,1.27,4.447514,29768.56200,NaN,NaN,-0.900000,6424.152176,47,207600.0
356,Belgium,2020,0.00,0.00,30.00,34.43,23.46,65.866425,57433.73000,NaN,NaN,-5.659660,45159.348220,383,30528.0
377,Belize,2020,258.71,0.00,0.38,0.00,0.24,38.709680,7226.43360,NaN,NaN,-14.010532,4115.177008,17,22966.0
398,Benin,2020,0.28,0.00,0.22,0.00,0.01,4.347826,2518.62100,NaN,NaN,3.848792,1291.040972,108,112622.0
419,Bermuda,2020,0.00,0.00,0.00,0.00,0.00,0.000000,46161.58600,NaN,NaN,-6.344080,107079.479800,1281,54.0
440,Bhutan,2020,3026.40,0.00,0.00,0.00,8.95,100.000000,26593.05900,NaN,NaN,-10.076341,3000.779327,20,38394.0
461,Bosnia and Herzegovina,2020,0.00,0.00,10.82,0.00,4.90,31.170483,19464.83600,NaN,NaN,-3.196950,6079.738285,64,51197.0
482,Botswana,2020,2.61,0.00,2.05,0.00,0.01,0.485437,8843.10700,NaN,NaN,-8.492894,6404.899932,4,581730.0
503,Brazil,2020,705.90,0.00,81.15,13.21,520.01,86.791340,15921.32700,NaN,NaN,-4.059048,6796.844542,25,8515770.0
524,Bulgaria,2020,0.00,0.00,16.12,16.63,7.47,59.920437,27993.87000,NaN,NaN,-4.387150,10079.203380,64,110879.0
545,Burkina Faso,2020,4.68,0.00,1.43,0.00,0.21,12.804878,878.98150,NaN,NaN,1.930325,857.932730,76,274200.0
566,Burundi,2020,4.83,0.00,0.11,0.00,0.24,68.571430,289.06625,NaN,NaN,0.297577,238.990726,463,27830.0
587,Cambodia,2020,95.03,0.00,3.83,0.00,4.62,54.674557,3918.63750,NaN,NaN,-3.147589,1543.669258,95,181035.0
608,Cameroon,2020,29.82,0.00,2.84,0.00,5.45,65.741860,1758.12060,NaN,NaN,0.491915,1537.130218,56,475440.0
629,Canada,2020,0.00,0.00,102.19,92.65,429.24,83.625496,100497.28000,NaN,NaN,-5.233024,43294.648160,4,9984670.0
650,Cayman Islands,2020,193.81,0.00,0.67,0.00,0.02,2.898551,41981.38000,NaN,NaN,-6.730287,85082.526860,274,264.0
671,Central African Republic,2020,3.97,0.00,0.00,0.00,0.15,100.000000,280.73853,NaN,NaN,0.829010,492.795871,8,622984.0
692,Chad,2020,0.20,0.00,0.28,0.00,0.01,3.448276,372.51090,NaN,NaN,-0.947305,659.270045,13,1284000.0
713,Chile,2020,669.29,0.00,43.69,0.00,34.06,43.807076,22925.92600,NaN,NaN,-5.771502,13231.704210,26,756096.0
734,China,2020,621.74,0.00,5184.13,366.20,2184.94,32.980618,29133.93600,NaN,NaN,2.347514,10434.775190,153,9596960.0
755,Colombia,2020,266.33,0.00,27.17,0.00,49.97,64.778330,10064.38900,NaN,NaN,-6.795758,5334.556042,46,1138910.0
776,Comoros,2020,1.66,0.00,0.13,0.00,0.00,0.000000,1578.06290,NaN,NaN,-0.128835,1420.661747,467,2235.0
797,Congo,2020,41.10,0.00,2.87,0.00,0.96,25.065275,2379.55600,NaN,NaN,NaN,NaN,18,2345409.0
818,Costa Rica,2020,613.34,0.00,0.19,0.00,11.55,98.381610,11486.32400,NaN,NaN,-4.063677,12140.854150,100,51100.0
839,Croatia,2020,0.00,0.00,4.69,0.00,8.55,64.577040,22304.44700,NaN,NaN,-8.099761,14134.162680,73,56594.0
860,Cuba,2020,105.79,0.00,15.47,0.00,3.13,16.827957,9007.18100,NaN,NaN,-10.948341,9477.852873,106,110860.0
881,Cyprus,2020,0.00,0.00,4.25,0.00,0.60,12.371135,22852.85200,NaN,NaN,-5.228988,27527.845310,131,9251.0
902,Czechia,2020,0.00,0.00,39.72,30.04,10.39,50.442917,42025.31000,NaN,NaN,NaN,NaN,136,78871.0
923,Denmark,2020,0.00,0.00,5.28,0.00,23.45,81.622000,29380.42200,NaN,NaN,-2.062125,61063.316430,137,43094.0
944,Djibouti,2020,0.37,0.00,0.05,0.00,0.00,0.000000,2701.79080,NaN,NaN,0.500000,3425.484176,43,23200.0
965,Dominica,2020,98.83,0.00,0.12,0.00,0.04,25.000000,10056.24600,NaN,NaN,-16.604912,7003.859021,96,751.0
986,Dominican Republic,2020,120.72,0.00,13.74,0.00,2.90,17.427885,9496.66800,NaN,NaN,-6.720239,7268.196910,225,48670.0
1007,Ecuador,2020,300.29,0.00,6.45,0.00,24.83,79.379790,10374.72700,NaN,NaN,-7.750123,5600.389615,71,283561.0
1028,Egypt,2020,58.35,0.00,168.46,0.00,20.83,11.004279,9153.98900,NaN,NaN,NaN,NaN,103,1001450.0
1049,El Salvador,2020,232.16,0.00,1.29,0.00,4.97,79.392970,6715.60800,NaN,NaN,-8.581312,3798.636521,313,21041.0
1070,Equatorial Guinea,2020,90.68,0.00,0.92,0.00,0.49,34.751774,11328.12300,NaN,NaN,-4.893356,7143.238705,50,28051.0
1087,Eritrea,2016,2.68,77.31,0.34,0.00,0.00,0.000000,715.03436,NaN,660.000026,NaN,NaN,35,117600.0
1088,Eritrea,2017,3.23,75.37,0.40,0.00,0.01,2.439024,778.28644,NaN,720.000029,NaN,NaN,35,117600.0
1089,Eritrea,2018,5.37,74.03,0.42,0.00,0.01,2.325581,876.14870,NaN,850.000024,NaN,NaN,35,117600.0
1090,Eritrea,2019,5.94,73.67,0.43,0.00,0.01,2.272727,936.47850,NaN,879.999995,NaN,NaN,35,117600.0
1091,Eritrea,2020,6.49,0.00,0.41,0.00,0.01,2.380952,881.58750,NaN,NaN,NaN,NaN,35,117600.0
1112,Estonia,2020,0.00,0.00,3.11,0.00,2.97,48.848686,44218.28000,NaN,NaN,-2.951069,23027.027000,31,45228.0
1133,Eswatini,2020,145.70,0.00,0.04,0.00,0.70,94.594600,5614.89060,NaN,NaN,-1.850525,3424.282212,67,17364.0
1154,Ethiopia,2020,40.99,0.00,0.01,0.00,14.22,99.929726,860.09990,NaN,NaN,6.056618,936.340461,115,1104300.0
1175,Fiji,2020,236.38,0.00,0.40,0.00,0.70,63.636364,9030.60600,NaN,NaN,-15.711804,5057.631913,49,18274.0

In [27]:

valores_nulos = df[df['energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
20,Afghanistan,2020,9.35,0.00,0.12,0.00,0.68,85.000000,702.88800,NaN,NaN,-2.351101,516.747871,60,652230.0
41,Albania,2020,0.00,0.00,0.00,0.00,5.31,100.000000,11158.00300,NaN,NaN,-3.955398,5246.292306,105,28748.0
62,Algeria,2020,15.64,0.00,72.01,0.00,0.72,0.989963,14933.80700,NaN,NaN,-5.100000,3306.858208,18,2381741.0
83,Angola,2020,115.43,0.00,4.49,0.00,12.10,72.935500,3527.16000,NaN,NaN,-5.399987,1776.166868,26,1246700.0
104,Antigua and Barbuda,2020,167.98,0.00,0.31,0.00,0.02,6.060606,27785.22700,NaN,NaN,-20.192371,13992.744480,223,443.0
125,Argentina,2020,311.28,0.00,91.58,10.06,37.05,33.967842,19314.06600,NaN,NaN,-9.895269,8579.017773,17,2780400.0
146,Armenia,2020,484.04,0.00,2.98,2.55,1.92,59.999996,17086.04700,NaN,NaN,-7.400000,4266.018074,104,29743.0
167,Aruba,2020,356.86,0.00,0.73,0.00,0.15,17.045456,43496.94000,NaN,NaN,NaN,NaN,590,179.0
188,Australia,2020,0.00,0.00,186.92,0.00,63.99,25.503168,61826.21000,NaN,NaN,-0.003837,51692.842750,3,7741220.0
209,Austria,2020,0.00,0.00,13.77,0.00,55.42,80.098274,45028.27000,NaN,NaN,-6.734514,48586.801320,109,83871.0
230,Azerbaijan,2020,127.35,0.00,23.16,0.00,1.22,5.004102,17803.62900,NaN,NaN,-4.300000,4221.407478,123,86600.0
251,Bahamas,2020,5.68,0.00,1.99,0.00,0.00,0.000000,33301.77000,NaN,NaN,NaN,NaN,41,13878.0
272,Bahrain,2020,6.13,0.00,29.85,0.00,0.01,0.033490,156095.80000,NaN,NaN,-5.085180,20409.952800,"2,239",765.0
293,Bangladesh,2020,3.12,0.00,74.41,0.00,1.31,1.730058,2730.07800,NaN,NaN,3.509136,1961.613749,"1,265",148460.0
314,Barbados,2020,174.06,0.00,0.93,0.00,0.07,7.000000,21577.82800,NaN,NaN,-18.979510,15373.854700,668,430.0
335,Belarus,2020,0.00,0.00,34.59,0.34,1.27,4.447514,29768.56200,NaN,NaN,-0.900000,6424.152176,47,207600.0
356,Belgium,2020,0.00,0.00,30.00,34.43,23.46,65.866425,57433.73000,NaN,NaN,-5.659660,45159.348220,383,30528.0
377,Belize,2020,258.71,0.00,0.38,0.00,0.24,38.709680,7226.43360,NaN,NaN,-14.010532,4115.177008,17,22966.0
398,Benin,2020,0.28,0.00,0.22,0.00,0.01,4.347826,2518.62100,NaN,NaN,3.848792,1291.040972,108,112622.0
419,Bermuda,2020,0.00,0.00,0.00,0.00,0.00,0.000000,46161.58600,NaN,NaN,-6.344080,107079.479800,1281,54.0
440,Bhutan,2020,3026.40,0.00,0.00,0.00,8.95,100.000000,26593.05900,NaN,NaN,-10.076341,3000.779327,20,38394.0
461,Bosnia and Herzegovina,2020,0.00,0.00,10.82,0.00,4.90,31.170483,19464.83600,NaN,NaN,-3.196950,6079.738285,64,51197.0
482,Botswana,2020,2.61,0.00,2.05,0.00,0.01,0.485437,8843.10700,NaN,NaN,-8.492894,6404.899932,4,581730.0
503,Brazil,2020,705.90,0.00,81.15,13.21,520.01,86.791340,15921.32700,NaN,NaN,-4.059048,6796.844542,25,8515770.0
524,Bulgaria,2020,0.00,0.00,16.12,16.63,7.47,59.920437,27993.87000,NaN,NaN,-4.387150,10079.203380,64,110879.0
545,Burkina Faso,2020,4.68,0.00,1.43,0.00,0.21,12.804878,878.98150,NaN,NaN,1.930325,857.932730,76,274200.0
566,Burundi,2020,4.83,0.00,0.11,0.00,0.24,68.571430,289.06625,NaN,NaN,0.297577,238.990726,463,27830.0
587,Cambodia,2020,95.03,0.00,3.83,0.00,4.62,54.674557,3918.63750,NaN,NaN,-3.147589,1543.669258,95,181035.0
608,Cameroon,2020,29.82,0.00,2.84,0.00,5.45,65.741860,1758.12060,NaN,NaN,0.491915,1537.130218,56,475440.0
629,Canada,2020,0.00,0.00,102.19,92.65,429.24,83.625496,100497.28000,NaN,NaN,-5.233024,43294.648160,4,9984670.0
650,Cayman Islands,2020,193.81,0.00,0.67,0.00,0.02,2.898551,41981.38000,NaN,NaN,-6.730287,85082.526860,274,264.0
671,Central African Republic,2020,3.97,0.00,0.00,0.00,0.15,100.000000,280.73853,NaN,NaN,0.829010,492.795871,8,622984.0
692,Chad,2020,0.20,0.00,0.28,0.00,0.01,3.448276,372.51090,NaN,NaN,-0.947305,659.270045,13,1284000.0
713,Chile,2020,669.29,0.00,43.69,0.00,34.06,43.807076,22925.92600,NaN,NaN,-5.771502,13231.704210,26,756096.0
734,China,2020,621.74,0.00,5184.13,366.20,2184.94,32.980618,29133.93600,NaN,NaN,2.347514,10434.775190,153,9596960.0
755,Colombia,2020,266.33,0.00,27.17,0.00,49.97,64.778330,10064.38900,NaN,NaN,-6.795758,5334.556042,46,1138910.0
776,Comoros,2020,1.66,0.00,0.13,0.00,0.00,0.000000,1578.06290,NaN,NaN,-0.128835,1420.661747,467,2235.0
797,Congo,2020,41.10,0.00,2.87,0.00,0.96,25.065275,2379.55600,NaN,NaN,NaN,NaN,18,2345409.0
818,Costa Rica,2020,613.34,0.00,0.19,0.00,11.55,98.381610,11486.32400,NaN,NaN,-4.063677,12140.854150,100,51100.0
839,Croatia,2020,0.00,0.00,4.69,0.00,8.55,64.577040,22304.44700,NaN,NaN,-8.099761,14134.162680,73,56594.0
860,Cuba,2020,105.79,0.00,15.47,0.00,3.13,16.827957,9007.18100,NaN,NaN,-10.948341,9477.852873,106,110860.0
881,Cyprus,2020,0.00,0.00,4.25,0.00,0.60,12.371135,22852.85200,NaN,NaN,-5.228988,27527.845310,131,9251.0
902,Czechia,2020,0.00,0.00,39.72,30.04,10.39,50.442917,42025.31000,NaN,NaN,NaN,NaN,136,78871.0
923,Denmark,2020,0.00,0.00,5.28,0.00,23.45,81.622000,29380.42200,NaN,NaN,-2.062125,61063.316430,137,43094.0
944,Djibouti,2020,0.37,0.00,0.05,0.00,0.00,0.000000,2701.79080,NaN,NaN,0.500000,3425.484176,43,23200.0
965,Dominica,2020,98.83,0.00,0.12,0.00,0.04,25.000000,10056.24600,NaN,NaN,-16.604912,7003.859021,96,751.0
986,Dominican Republic,2020,120.72,0.00,13.74,0.00,2.90,17.427885,9496.66800,NaN,NaN,-6.720239,7268.196910,225,48670.0
1007,Ecuador,2020,300.29,0.00,6.45,0.00,24.83,79.379790,10374.72700,NaN,NaN,-7.750123,5600.389615,71,283561.0
1028,Egypt,2020,58.35,0.00,168.46,0.00,20.83,11.004279,9153.98900,NaN,NaN,NaN,NaN,103,1001450.0
1049,El Salvador,2020,232.16,0.00,1.29,0.00,4.97,79.392970,6715.60800,NaN,NaN,-8.581312,3798.636521,313,21041.0
1070,Equatorial Guinea,2020,90.68,0.00,0.92,0.00,0.49,34.751774,11328.12300,NaN,NaN,-4.893356,7143.238705,50,28051.0
1087,Eritrea,2016,2.68,77.31,0.34,0.00,0.00,0.000000,715.03436,NaN,660.000026,NaN,NaN,35,117600.0
1088,Eritrea,2017,3.23,75.37,0.40,0.00,0.01,2.439024,778.28644,NaN,720.000029,NaN,NaN,35,117600.0
1089,Eritrea,2018,5.37,74.03,0.42,0.00,0.01,2.325581,876.14870,NaN,850.000024,NaN,NaN,35,117600.0
1090,Eritrea,2019,5.94,73.67,0.43,0.00,0.01,2.272727,936.47850,NaN,879.999995,NaN,NaN,35,117600.0
1091,Eritrea,2020,6.49,0.00,0.41,0.00,0.01,2.380952,881.58750,NaN,NaN,NaN,NaN,35,117600.0
1112,Estonia,2020,0.00,0.00,3.11,0.00,2.97,48.848686,44218.28000,NaN,NaN,-2.951069,23027.027000,31,45228.0
1133,Eswatini,2020,145.70,0.00,0.04,0.00,0.70,94.594600,5614.89060,NaN,NaN,-1.850525,3424.282212,67,17364.0
1154,Ethiopia,2020,40.99,0.00,0.01,0.00,14.22,99.929726,860.09990,NaN,NaN,6.056618,936.340461,115,1104300.0
1175,Fiji,2020,236.38,0.00,0.40,0.00,0.70,63.636364,9030.60600,NaN,NaN,-15.711804,5057.631913,49,18274.0

In [28]:
valores_nulos.tail(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
2576,Papua New Guinea,2020,37.26,0.00,3.36,0.00,1.28,27.586208,2163.87040,NaN,NaN,-3.500000,2757.217530,20,462840.0
2597,Paraguay,2020,1238.30,0.00,0.07,0.00,46.43,99.849464,18493.11500,NaN,NaN,-0.565695,5001.072760,18,406752.0
2618,Peru,2020,201.09,0.00,19.10,0.00,33.72,63.839455,8365.43200,NaN,NaN,-11.148812,6126.874540,26,1285216.0
2639,Philippines,2020,62.39,0.00,79.27,0.00,23.21,22.648321,4565.33840,NaN,NaN,-9.573030,3298.829586,368,300000.0
2660,Poland,2020,0.00,0.00,128.91,0.00,28.23,17.964872,29514.13300,NaN,NaN,-2.540659,15720.994660,124,312685.0
2681,Portugal,2020,0.00,0.00,21.43,0.00,30.11,58.420643,25782.07800,NaN,NaN,-8.442456,22176.296710,111,92212.0
2702,Puerto Rico,2020,126.71,0.00,16.67,0.00,0.47,2.742124,21459.73000,NaN,NaN,-3.903305,32290.921140,368,9104.0
2723,Qatar,2020,14.96,0.00,44.63,0.00,0.02,0.044793,184074.56000,NaN,NaN,-3.557604,50124.385940,248,11586.0
2744,Romania,2020,0.00,0.00,19.54,11.47,24.61,64.868760,18998.81200,NaN,NaN,-3.930454,12896.088620,84,238391.0
2765,Rwanda,2020,10.92,0.00,0.32,0.00,0.59,64.835160,496.89820,NaN,NaN,-3.355472,797.855521,525,26338.0
2786,Saint Kitts and Nevis,2020,77.83,0.00,0.20,0.00,0.01,4.761905,19642.78300,NaN,NaN,NaN,NaN,205,261.0
2807,Saint Lucia,2020,20.89,0.00,0.33,0.00,0.00,0.000000,12810.41500,NaN,NaN,NaN,NaN,301,616.0
2828,Saint Vincent and the Grenadines,2020,67.69,0.00,0.11,0.00,0.04,26.666666,7788.49600,NaN,NaN,NaN,NaN,284,389.0
2849,Samoa,2020,141.80,0.00,0.10,0.00,0.06,37.500000,7222.19040,NaN,NaN,-2.592608,4067.843459,70,2831.0
2870,Sao Tome and Principe,2020,12.11,0.00,0.09,0.00,0.01,10.000000,3207.42300,NaN,NaN,3.089726,2157.840446,242,836.0
2891,Saudi Arabia,2020,11.85,0.00,337.82,0.00,0.21,0.062125,80309.99000,NaN,NaN,-4.106583,20110.316190,16,2149690.0
2912,Senegal,2020,14.69,0.00,4.23,0.00,1.00,19.120459,2532.41260,NaN,NaN,1.499763,1471.830962,87,196722.0
2926,Serbia,2020,0.00,0.00,27.02,0.00,10.21,27.424120,26211.98400,NaN,NaN,-0.944597,7720.510572,100,77474.0
2947,Seychelles,2020,99.53,0.00,0.53,0.00,0.07,11.666666,43703.28000,NaN,NaN,-10.770921,10764.420420,214,455.0
2968,Sierra Leone,2020,12.42,0.00,0.02,0.00,0.19,90.476200,480.52710,NaN,NaN,-1.968948,509.376594,111,71740.0
2989,Singapore,2020,93.64,0.00,50.04,0.00,0.83,1.631610,154256.30000,NaN,NaN,-5.391021,59797.752180,"8,358",716.0
3010,Slovakia,2020,0.00,0.00,6.22,15.44,6.85,78.183090,33193.33000,NaN,NaN,NaN,NaN,114,49035.0
3031,Slovenia,2020,0.00,0.00,4.96,6.35,5.58,70.633514,36542.86700,NaN,NaN,-4.229261,25517.330670,103,20273.0
3052,Solomon Islands,2020,5.28,0.00,0.10,0.00,0.00,0.000000,1877.31910,NaN,NaN,-4.317260,2250.601164,25,28896.0
3073,Somalia,2020,1.64,0.00,0.35,0.00,0.03,7.894737,212.09578,NaN,NaN,2.440211,438.255166,25,637657.0
3094,South Africa,2020,162.50,0.00,197.50,11.62,12.83,11.015995,23568.95100,NaN,NaN,-6.431975,5655.867654,49,1219090.0
3098,South Sudan,2016,0.04,28.79,0.49,0.00,0.00,0.000000,698.38540,NaN,1730.000019,NaN,NaN,18,644329.0
3099,South Sudan,2017,0.04,28.63,0.51,0.00,0.00,0.000000,635.44260,NaN,1519.999981,NaN,NaN,18,644329.0
3100,South Sudan,2018,0.05,28.65,0.55,0.00,0.01,1.785714,671.75750,NaN,1549.999952,NaN,NaN,18,644329.0
3101,South Sudan,2019,0.06,26.65,0.55,0.00,0.01,1.785714,747.48596,NaN,1700.000048,NaN,NaN,18,644329.0
3102,South Sudan,2020,0.06,0.00,0.53,0.00,0.01,1.851852,703.13510,NaN,NaN,NaN,NaN,18,644329.0
3123,Spain,2020,0.00,0.00,87.64,58.30,113.79,66.257260,30391.29000,NaN,NaN,-10.822886,27063.193920,94,505370.0
3144,Sri Lanka,2020,109.83,0.00,9.64,0.00,5.94,38.125800,4853.11040,NaN,NaN,-3.569076,3680.673477,341,65610.0
3165,Sudan,2020,48.44,0.00,5.68,0.00,10.79,65.513054,2378.22800,NaN,NaN,-3.629806,486.418816,25,1861484.0
3186,Suriname,2020,325.78,0.00,0.94,0.00,0.98,51.041668,20356.20500,NaN,NaN,-15.907951,4916.605666,4,163820.0
3207,Sweden,2020,0.00,0.00,2.44,49.20,112.15,98.510300,59395.52300,NaN,NaN,-2.948128,52274.408790,25,450295.0
3228,Switzerland,2020,0.00,0.00,3.62,22.99,40.79,94.629080,35766.37500,NaN,NaN,-2.392826,87097.036450,219,41277.0
3249,Tajikistan,2020,552.88,0.00,1.62,0.00,18.11,91.789154,7819.38960,NaN,NaN,4.500000,859.137961,68,144100.0
3270,Thailand,2020,171.79,0.00,154.52,0.00,24.73,13.796373,19298.08600,NaN,NaN,-6.098984,7186.874092,137,513120.0
3291,Togo,2020,8.72,0.00,0.43,0.00,0.15,25.862072,1152.51860,NaN,NaN,1.752825,914.950793,152,56785.0
3312,Tonga,2020,73.33,0.00,0.06,0.00,0.01,14.285714,6542.06600,NaN,NaN,0.654699,4624.823449,147,747.0
3333,Trinidad and Tobago,2020,2.15,0.00,8.20,0.00,0.01,0.121803,108794.93000,NaN,NaN,-7.853940,15425.635110,273,5128.0
3354,Tunisia,2020,33.92,0.00,18.73,0.00,0.85,4.341165,9290.70200,NaN,NaN,-9.182373,3521.591948,76,163610.0
3375,Turkey,2020,585.71,0.00,177.08,0.00,128.34,42.020820,21435.07000,NaN,NaN,1.793551,8536.433320,110,783562.0
3396,Turkmenistan,2020,0.20,0.00,20.11,0.00,0.00,0.000000,67626.92000,NaN,NaN,NaN,NaN,13,488100.0
3417,Tuvalu,2020,196.07,0.00,0.00,0.00,0.00,0.000000,0.00000,NaN,NaN,4.400000,4143.109753,393,26.0
3438,Uganda,2020,25.89,0.00,0.13,0.00,4.32,97.078660,766.41430,NaN,NaN,2.951306,822.027681,229,241038.0
3459,Ukraine,2020,0.00,0.00,54.50,76.20,17.56,63.240257,20916.84400,NaN,NaN,-4.000006,3724.938437,75,603550.0
3480,United Arab Emirates,2020,256.84,0.00,119.49,1.56,5.50,5.578823,126073.66000,NaN,NaN,-6.134501,36284.555240,118,83600.0
3501,United Kingdom,2020,0.00,0.00,124.78,50.85,131.74,59.403976,29425.54000,NaN,NaN,-9.396160,41059.168810,281,243610.0
3522,United States,2020,0.00,0.00,2431.90,789.88,821.40,39.851800,73236.14000,NaN,NaN,-3.404592,63593.443620,36,9833517.0
3543,Uruguay,2020,1075.17,0.00,2.40,0.00,11.14,82.274740,17631.44000,NaN,NaN,-5.858721,15438.411670,20,176215.0
3564,Uzbekistan,2020,60.02,0.00,50.93,0.00,5.01,8.956025,15860.60900,NaN,NaN,1.714771,1750.697113,79,447400.0
3585,Vanuatu,2020,37.84,0.00,0.05,0.00,0.02,28.571428,2923.53800,NaN,NaN,-6.813991,2870.089300,25,12189.0
3602,Yemen,2016,2.94,2.48,4.36,0.00,0.16,3.539823,1432.55220,NaN,NaN,NaN,NaN,56,527968.0
3603,Yemen,2017,3.59,2.80,3.63,0.00,0.19,4.973822,1288.87670,NaN,NaN,NaN,NaN,56,527968.0
3604,Yemen,2018,8.77,3.60,2.82,0.00,0.48,14.545455,1170.72610,NaN,NaN,NaN,NaN,56,527968.0
3605,Yemen,2019,8.57,3.11,2.93,0.00,0.48,14.076246,1475.98520,NaN,NaN,NaN,NaN,56,527968.0
3606,Yemen,2020,8.48,0.00,2.74,0.00,0.49,15.170279,1092.00210,NaN,NaN,NaN,NaN,56,527968.0
3627,Zambia,2020,138.23,0.00,2.00,0.00,13.10,86.754970,3099.08300,NaN,NaN,-2.785055,985.132436,25,752618.0

In [29]:
df['energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)'] = df['energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.000000,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.000000,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.000460,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.000150,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.000110,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.000230,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,NaN,-6.248748,1214.509820,38,390757.0

In [30]:
valores_nulos = df[df['value_co2_emissions_kt_by_country'].isnull()]

valores_nulos.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
20,Afghanistan,2020,9.35,0.00,0.12,0.00,0.68,85.000000,702.88800,0.00,NaN,-2.351101,516.747871,60,652230.0
41,Albania,2020,0.00,0.00,0.00,0.00,5.31,100.000000,11158.00300,0.00,NaN,-3.955398,5246.292306,105,28748.0
62,Algeria,2020,15.64,0.00,72.01,0.00,0.72,0.989963,14933.80700,0.00,NaN,-5.100000,3306.858208,18,2381741.0
83,Angola,2020,115.43,0.00,4.49,0.00,12.10,72.935500,3527.16000,0.00,NaN,-5.399987,1776.166868,26,1246700.0
104,Antigua and Barbuda,2020,167.98,0.00,0.31,0.00,0.02,6.060606,27785.22700,0.00,NaN,-20.192371,13992.744480,223,443.0
125,Argentina,2020,311.28,0.00,91.58,10.06,37.05,33.967842,19314.06600,0.00,NaN,-9.895269,8579.017773,17,2780400.0
146,Armenia,2020,484.04,0.00,2.98,2.55,1.92,59.999996,17086.04700,0.00,NaN,-7.400000,4266.018074,104,29743.0
164,Aruba,2017,361.61,6.70,0.79,0.00,0.14,15.053763,51509.81000,3.13,NaN,1.999999,29350.805020,590,179.0
165,Aruba,2018,359.96,8.02,0.76,0.00,0.15,16.483517,49515.11300,3.07,NaN,NaN,30253.279360,590,179.0
166,Aruba,2019,358.39,7.48,0.77,0.00,0.15,16.304348,51107.84400,3.20,NaN,NaN,NaN,590,179.0
167,Aruba,2020,356.86,0.00,0.73,0.00,0.15,17.045456,43496.94000,0.00,NaN,NaN,NaN,590,179.0
188,Australia,2020,0.00,0.00,186.92,0.00,63.99,25.503168,61826.21000,0.00,NaN,-0.003837,51692.842750,3,7741220.0
209,Austria,2020,0.00,0.00,13.77,0.00,55.42,80.098274,45028.27000,0.00,NaN,-6.734514,48586.801320,109,83871.0
230,Azerbaijan,2020,127.35,0.00,23.16,0.00,1.22,5.004102,17803.62900,0.00,NaN,-4.300000,4221.407478,123,86600.0
231,Bahamas,2000,0.00,0.00,1.57,0.00,0.00,0.000000,50650.19000,2.33,NaN,NaN,NaN,41,13878.0
232,Bahamas,2001,0.00,0.42,1.63,0.00,0.00,0.000000,50899.52700,2.19,NaN,NaN,NaN,41,13878.0
233,Bahamas,2002,0.00,0.38,1.72,0.00,0.00,0.000000,52098.81000,2.23,NaN,NaN,NaN,41,13878.0
234,Bahamas,2003,0.00,1.54,1.81,0.00,0.00,0.000000,35908.11700,2.32,NaN,NaN,NaN,41,13878.0
235,Bahamas,2004,0.00,1.59,1.79,0.00,0.00,0.000000,39267.47000,2.27,NaN,NaN,NaN,41,13878.0
236,Bahamas,2005,0.00,1.71,1.89,0.00,0.00,0.000000,37244.63700,2.10,NaN,NaN,NaN,41,13878.0
237,Bahamas,2006,0.00,2.01,1.93,0.00,0.00,0.000000,42663.53000,2.00,NaN,NaN,NaN,41,13878.0
238,Bahamas,2007,0.30,3.54,2.05,0.00,0.00,0.000000,48444.41000,2.00,NaN,NaN,NaN,41,13878.0
239,Bahamas,2008,0.29,1.97,2.05,0.00,0.00,0.000000,46670.27300,2.08,NaN,NaN,NaN,41,13878.0
240,Bahamas,2009,0.57,1.83,1.95,0.00,0.00,0.000000,34584.95700,2.23,NaN,NaN,NaN,41,13878.0
241,Bahamas,2010,0.85,1.65,1.89,0.00,0.00,0.000000,35531.06000,2.14,NaN,NaN,NaN,41,13878.0
242,Bahamas,2011,1.14,1.42,1.93,0.00,0.00,0.000000,30982.48600,2.35,NaN,NaN,NaN,41,13878.0
243,Bahamas,2012,1.71,1.18,1.79,0.00,0.00,0.000000,35422.55500,2.50,NaN,NaN,NaN,41,13878.0
244,Bahamas,2013,1.70,0.96,1.77,0.00,0.00,0.000000,32656.57200,2.98,NaN,NaN,NaN,41,13878.0
245,Bahamas,2014,3.44,1.14,1.81,0.00,0.00,0.000000,31772.06600,2.65,NaN,NaN,NaN,41,13878.0
246,Bahamas,2015,3.47,1.54,1.88,0.00,0.00,0.000000,30096.48000,2.33,NaN,NaN,NaN,41,13878.0
247,Bahamas,2016,3.84,1.53,1.85,0.00,0.00,0.000000,31247.09600,2.12,NaN,NaN,NaN,41,13878.0
248,Bahamas,2017,3.66,1.44,1.87,0.00,0.00,0.000000,36977.28000,2.18,NaN,NaN,NaN,41,13878.0
249,Bahamas,2018,3.54,1.02,2.14,0.00,0.00,0.000000,39876.79000,2.72,NaN,NaN,NaN,41,13878.0
250,Bahamas,2019,5.88,1.14,2.10,0.00,0.00,0.000000,39636.06600,2.53,NaN,NaN,NaN,41,13878.0
251,Bahamas,2020,5.68,0.00,1.99,0.00,0.00,0.000000,33301.77000,0.00,NaN,NaN,NaN,41,13878.0
272,Bahrain,2020,6.13,0.00,29.85,0.00,0.01,0.033490,156095.80000,0.00,NaN,-5.085180,20409.952800,"2,239",765.0
293,Bangladesh,2020,3.12,0.00,74.41,0.00,1.31,1.730058,2730.07800,0.00,NaN,3.509136,1961.613749,"1,265",148460.0
314,Barbados,2020,174.06,0.00,0.93,0.00,0.07,7.000000,21577.82800,0.00,NaN,-18.979510,15373.854700,668,430.0
335,Belarus,2020,0.00,0.00,34.59,0.34,1.27,4.447514,29768.56200,0.00,NaN,-0.900000,6424.152176,47,207600.0
356,Belgium,2020,0.00,0.00,30.00,34.43,23.46,65.866425,57433.73000,0.00,NaN,-5.659660,45159.348220,383,30528.0
377,Belize,2020,258.71,0.00,0.38,0.00,0.24,38.709680,7226.43360,0.00,NaN,-14.010532,4115.177008,17,22966.0
398,Benin,2020,0.28,0.00,0.22,0.00,0.01,4.347826,2518.62100,0.00,NaN,3.848792,1291.040972,108,112622.0
416,Bermuda,2017,0.00,0.64,0.00,0.00,0.00,0.000000,49395.46000,1.77,NaN,3.611420,111820.581500,1281,54.0
417,Bermuda,2018,0.00,0.67,0.00,0.00,0.00,0.000000,50863.38000,1.97,NaN,-0.432801,113023.185600,1281,54.0
418,Bermuda,2019,0.00,0.84,0.00,0.00,0.00,0.000000,50639.29300,1.65,NaN,0.459890,117098.446300,1281,54.0
419,Bermuda,2020,0.00,0.00,0.00,0.00,0.00,0.000000,46161.58600,0.00,NaN,-6.344080,107079.479800,1281,54.0
440,Bhutan,2020,3026.40,0.00,0.00,0.00,8.95,100.000000,26593.05900,0.00,NaN,-10.076341,3000.779327,20,38394.0
461,Bosnia and Herzegovina,2020,0.00,0.00,10.82,0.00,4.90,31.170483,19464.83600,0.00,NaN,-3.196950,6079.738285,64,51197.0
482,Botswana,2020,2.61,0.00,2.05,0.00,0.01,0.485437,8843.10700,0.00,NaN,-8.492894,6404.899932,4,581730.0
503,Brazil,2020,705.90,0.00,81.15,13.21,520.01,86.791340,15921.32700,0.00,NaN,-4.059048,6796.844542,25,8515770.0
524,Bulgaria,2020,0.00,0.00,16.12,16.63,7.47,59.920437,27993.87000,0.00,NaN,-4.387150,10079.203380,64,110879.0
545,Burkina Faso,2020,4.68,0.00,1.43,0.00,0.21,12.804878,878.98150,0.00,NaN,1.930325,857.932730,76,274200.0
566,Burundi,2020,4.83,0.00,0.11,0.00,0.24,68.571430,289.06625,0.00,NaN,0.297577,238.990726,463,27830.0
587,Cambodia,2020,95.03,0.00,3.83,0.00,4.62,54.674557,3918.63750,0.00,NaN,-3.147589,1543.669258,95,181035.0
608,Cameroon,2020,29.82,0.00,2.84,0.00,5.45,65.741860,1758.12060,0.00,NaN,0.491915,1537.130218,56,475440.0
629,Canada,2020,0.00,0.00,102.19,92.65,429.24,83.625496,100497.28000,0.00,NaN,-5.233024,43294.648160,4,9984670.0
647,Cayman Islands,2017,138.30,0.01,0.65,0.00,0.01,1.515151,46465.98000,1.87,NaN,3.184043,81513.163020,274,264.0
648,Cayman Islands,2018,154.54,0.01,0.64,0.00,0.01,1.538462,42507.16400,1.90,NaN,4.194341,86059.739220,274,264.0
649,Cayman Islands,2019,170.81,0.00,0.68,0.00,0.02,2.857143,50531.71000,2.06,NaN,3.817100,91392.642590,274,264.0
650,Cayman Islands,2020,193.81,0.00,0.67,0.00,0.02,2.898551,41981.38000,0.00,NaN,-6.730287,85082.526860,274,264.0

In [31]:
df['value_co2_emissions_kt_by_country'] = df['value_co2_emissions_kt_by_country'].fillna('unknown')

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.0,NaN,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.0,NaN,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,NaN,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.00046,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.00015,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.00011,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.00023,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,unknown,-6.248748,1214.509820,38,390757.0

In [32]:
df['value_co2_emissions_kt_by_country'].tail(60)

3589        unknown
3590        unknown
3591        unknown
3592        unknown
3593        unknown
3594        unknown
3595        unknown
3596        unknown
3597        unknown
3598        unknown
3599        unknown
3600        unknown
3601        unknown
3602        unknown
3603        unknown
3604        unknown
3605        unknown
3606        unknown
3607         1810.0
3608         1840.0
3609    1919.999957
3610    2079.999924
3611    2109.999895
3612    2289.999962
3613    2180.000067
3614    1980.000019
3615    2190.000057
3616     2490.00001
3617    2660.000086
3618    3049.999952
3619     4030.00021
3620    4239.999771
3621    4690.000057
3622    4960.000038
3623    5320.000172
3624    6809.999943
3625    7730.000019
3626    6800.000191
3627        unknown
3628        13700.0
3629        13900.0
3630    12489.99977
3631    10180.00031
3632    9770.000458
3633    10510.00023
3634    9829.999924
3635    9760.000229
3636    7599.999905
3637         7750.0
3638    9600.000381
3639    11409.99985
3640    12010.00023
3641    12279.99973
3642    12079.99992
3643    12430.00031
3644    11020.00046
3645    10340.00015
3646    12380.00011
3647    11760.00023
3648        unknown
Name: value_co2_emissions_kt_by_country, dtype: object

In [33]:
valores_nulos = df[df['gdp_growth'].isnull()]

valores_nulos.tail(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
2992,Slovakia,2002,0.00,5.48,8.81,17.95,5.42,72.622750,42124.30000,8.610000,unknown,NaN,NaN,114,49035.0
2993,Slovakia,2003,0.00,5.35,9.52,17.86,3.58,69.250650,40913.17000,8.120000,unknown,NaN,NaN,114,49035.0
2994,Slovakia,2004,0.00,6.25,9.29,17.03,4.13,69.490970,40008.50800,7.600000,unknown,NaN,NaN,114,49035.0
2995,Slovakia,2005,0.00,6.31,8.93,17.73,4.68,71.506065,42086.47300,7.310000,unknown,NaN,NaN,114,49035.0
2996,Slovakia,2006,0.00,6.57,8.39,18.01,4.81,73.117590,40946.38300,6.670000,unknown,NaN,NaN,114,49035.0
2997,Slovakia,2007,0.00,8.23,7.57,15.33,4.93,72.799140,38418.40600,5.760000,unknown,NaN,NaN,114,49035.0
2998,Slovakia,2008,0.00,7.63,7.46,16.70,4.57,74.034110,39431.95000,5.600000,unknown,NaN,NaN,114,49035.0
2999,Slovakia,2009,0.00,10.00,6.89,14.08,4.92,73.387410,35687.54000,5.410000,unknown,NaN,NaN,114,49035.0
3000,Slovakia,2010,0.00,10.28,6.90,14.57,5.95,74.835884,38080.72700,5.450000,unknown,NaN,NaN,114,49035.0
3001,Slovakia,2011,0.00,10.36,7.80,15.41,5.00,72.350235,36591.31000,5.150000,unknown,NaN,NaN,114,49035.0
3002,Slovakia,2012,0.00,10.47,7.28,15.49,5.47,74.220960,35105.08600,4.860000,unknown,NaN,NaN,114,49035.0
3003,Slovakia,2013,0.00,10.68,6.36,15.72,6.36,77.637130,35936.51000,4.910000,unknown,NaN,NaN,114,49035.0
3004,Slovakia,2014,0.00,12.24,5.30,15.50,6.24,80.399410,33419.59400,4.500000,unknown,NaN,NaN,114,49035.0
3005,Slovakia,2015,0.00,13.41,5.34,15.15,6.05,79.879425,33734.29000,4.410000,unknown,NaN,NaN,114,49035.0
3006,Slovakia,2016,0.00,13.09,5.28,14.77,6.63,80.209890,34015.23400,4.350000,unknown,NaN,NaN,114,49035.0
3007,Slovakia,2017,0.00,12.43,5.67,15.08,6.54,79.223160,35774.91000,4.450000,unknown,NaN,NaN,114,49035.0
3008,Slovakia,2018,0.00,12.43,5.92,14.84,5.81,77.719230,35121.08600,4.280000,unknown,NaN,NaN,114,49035.0
3009,Slovakia,2019,0.00,17.64,6.26,15.28,6.65,77.793540,33892.78000,4.110000,unknown,NaN,NaN,114,49035.0
3010,Slovakia,2020,0.00,0.00,6.22,15.44,6.85,78.183090,33193.33000,0.000000,unknown,NaN,NaN,114,49035.0
3053,Somalia,2000,0.00,93.28,0.23,0.00,0.00,0.000000,340.10217,11.220000,490.0,NaN,NaN,25,637657.0
3054,Somalia,2001,0.00,93.26,0.25,0.00,0.00,0.000000,332.43317,11.320000,510.0,NaN,NaN,25,637657.0
3055,Somalia,2002,0.00,92.58,0.26,0.00,0.00,0.000000,346.37854,11.390000,569.999993,NaN,NaN,25,637657.0
3056,Somalia,2003,0.00,92.80,0.26,0.00,0.00,0.000000,334.05520,11.510000,579.999983,NaN,NaN,25,637657.0
3057,Somalia,2004,0.00,93.00,0.26,0.00,0.00,0.000000,322.42703,11.480000,579.999983,NaN,NaN,25,637657.0
3058,Somalia,2005,0.00,93.30,0.27,0.00,0.00,0.000000,314.66333,11.470000,579.999983,NaN,NaN,25,637657.0
3059,Somalia,2006,0.00,93.47,0.28,0.00,0.00,0.000000,307.72528,11.600000,579.999983,NaN,NaN,25,637657.0
3060,Somalia,2007,0.00,93.02,0.29,0.00,0.00,0.000000,302.79350,11.530000,620.000005,NaN,NaN,25,637657.0
3061,Somalia,2008,0.00,93.37,0.30,0.00,0.00,0.000000,291.03380,11.740000,620.000005,NaN,NaN,25,637657.0
3062,Somalia,2009,0.00,93.63,0.31,0.00,0.00,0.000000,283.20413,11.820000,610.000014,NaN,NaN,25,637657.0
3063,Somalia,2010,0.00,93.57,0.31,0.00,0.00,0.000000,283.12300,11.870000,629.999995,NaN,NaN,25,637657.0
3064,Somalia,2011,0.00,93.65,0.31,0.00,0.00,0.000000,278.71530,11.790000,629.999995,NaN,NaN,25,637657.0
3065,Somalia,2012,0.17,93.90,0.32,0.00,0.00,0.000000,274.60495,11.680000,629.999995,NaN,NaN,25,637657.0
3066,Somalia,2013,0.17,94.40,0.33,0.00,0.00,0.000000,265.80110,11.950000,649.999976,NaN,350.168162,25,637657.0
3098,South Sudan,2016,0.04,28.79,0.49,0.00,0.00,0.000000,698.38540,0.000000,1730.000019,NaN,NaN,18,644329.0
3099,South Sudan,2017,0.04,28.63,0.51,0.00,0.00,0.000000,635.44260,0.000000,1519.999981,NaN,NaN,18,644329.0
3100,South Sudan,2018,0.05,28.65,0.55,0.00,0.01,1.785714,671.75750,0.000000,1549.999952,NaN,NaN,18,644329.0
3101,South Sudan,2019,0.06,26.65,0.55,0.00,0.01,1.785714,747.48596,0.000000,1700.000048,NaN,NaN,18,644329.0
3102,South Sudan,2020,0.06,0.00,0.53,0.00,0.01,1.851852,703.13510,0.000000,unknown,NaN,NaN,18,644329.0
3396,Turkmenistan,2020,0.20,0.00,20.11,0.00,0.00,0.000000,67626.92000,0.000000,unknown,NaN,NaN,13,488100.0
3586,Yemen,2000,0.00,0.95,3.21,0.00,0.00,0.000000,3228.21040,2.823132,unknown,NaN,NaN,56,527968.0
3587,Yemen,2001,0.00,0.89,3.42,0.00,0.00,0.000000,3380.40530,3.016477,unknown,NaN,NaN,56,527968.0
3588,Yemen,2002,0.00,0.90,3.54,0.00,0.00,0.000000,3320.32420,2.811401,unknown,NaN,NaN,56,527968.0
3589,Yemen,2003,0.00,0.78,3.85,0.00,0.00,0.000000,3707.22220,3.010832,unknown,NaN,NaN,56,527968.0
3590,Yemen,2004,0.00,0.75,4.10,0.00,0.00,0.000000,3811.39720,3.160727,unknown,NaN,NaN,56,527968.0
3591,Yemen,2005,0.00,0.74,4.48,0.00,0.00,0.000000,3906.30830,3.188304,unknown,NaN,NaN,56,527968.0
3592,Yemen,2006,0.00,0.76,5.06,0.00,0.00,0.000000,3788.24560,3.308474,unknown,NaN,NaN,56,527968.0
3593,Yemen,2007,0.00,0.76,5.67,0.00,0.00,0.000000,3902.28610,3.133247,unknown,NaN,NaN,56,527968.0
3594,Yemen,2008,0.04,0.74,6.15,0.00,0.00,0.000000,3976.89010,3.176676,unknown,NaN,NaN,56,527968.0
3595,Yemen,2009,0.04,0.70,6.34,0.00,0.00,0.000000,4277.22360,3.380211,unknown,NaN,NaN,56,527968.0
3596,Yemen,2010,0.04,0.78,7.29,0.00,0.00,0.000000,4030.75850,3.165451,unknown,NaN,NaN,56,527968.0
3597,Yemen,2011,0.05,0.93,5.83,0.00,0.00,0.000000,3289.45120,3.161177,unknown,NaN,NaN,56,527968.0
3598,Yemen,2012,0.06,1.08,6.65,0.00,0.00,0.000000,2769.04000,2.790347,unknown,NaN,NaN,56,527968.0
3599,Yemen,2013,0.09,0.76,7.99,0.00,0.00,0.000000,3797.82900,3.693557,unknown,NaN,NaN,56,527968.0
3600,Yemen,2014,0.19,0.76,7.19,0.00,0.01,0.138889,3495.32900,3.211405,unknown,NaN,NaN,56,527968.0
3601,Yemen,2015,2.26,1.96,5.81,0.00,0.12,2.023609,1837.10290,2.050356,unknown,NaN,NaN,56,527968.0
3602,Yemen,2016,2.94,2.48,4.36,0.00,0.16,3.539823,1432.55220,0.000000,unknown,NaN,NaN,56,527968.0
3603,Yemen,2017,3.59,2.80,3.63,0.00,0.19,4.973822,1288.87670,0.000000,unknown,NaN,NaN,56,527968.0
3604,Yemen,2018,8.77,3.60,2.82,0.00,0.48,14.545455,1170.72610,0.000000,unknown,NaN,NaN,56,527968.0
3605,Yemen,2019,8.57,3.11,2.93,0.00,0.48,14.076246,1475.98520,0.000000,unknown,NaN,NaN,56,527968.0
3606,Yemen,2020,8.48,0.00,2.74,0.00,0.49,15.170279,1092.00210,0.000000,unknown,NaN,NaN,56,527968.0

In [34]:
df.loc[df['country'].isin(['Yemen', 'Somalia','Slovakia']), 'gdp_growth'] = df.loc[df['country'].isin(['Yemen', 'Somalia','Slovakia']), 'gdp_growth'].fillna(0)

In [35]:
df.loc[df['country'].isin(['Saint Kitts and Nevis', 'Saint Lucia','Saint Vincent and the Grenadines','Sao Tome and Principe']), 'gdp_growth'] = df.loc[df['country'].isin(['Saint Kitts and Nevis', 'Saint Lucia','Saint Vincent and the Grenadines','Sao Tome and Principe']), 'gdp_growth'].fillna(0)

In [36]:
df.loc[df['country'].isin(['Gambia', 'Saint Lucia','Kyrgyzstan','New Caledonia','South Sudan']), 'gdp_growth'] = df.loc[df['country'].isin(['Gambia', 'Saint Lucia','Kyrgyzstan','New Caledonia','South Sudan']), 'gdp_growth'].fillna(0)

In [37]:
df.loc[df['country'].isin(['Nauru', 'Czechia','Egypt','Djibouti','Eritrea']), 'gdp_growth'] = df.loc[df['country'].isin(['Nauru', 'Czechia','Egypt','Djibouti','Eritrea']), 'gdp_growth'].fillna(0)

In [38]:
df['gdp_growth'] = df['gdp_growth'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.0,0.000000,NaN,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.0,0.000000,NaN,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,0.000000,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.00046,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.00015,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.00011,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.00023,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,unknown,-6.248748,1214.509820,38,390757.0

In [39]:
valores_nulos = df[df['gdp_growth'].isnull()]

valores_nulos.tail(60)

Empty DataFrame
Columns: [country, year, renewable_electricity_generating_capacity_per_capita, renewable_energy_share_in_the_total_final_energy_consumption_(%), electricity_from_fossil_fuels_(twh), electricity_from_nuclear_(twh), electricity_from_renewables_(twh), low_carbon_electricity_(%_electricity), primary_energy_consumption_per_capita_(kwh/person), energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp), value_co2_emissions_kt_by_country, gdp_growth, gdp_per_capita, density\n(p/km2), land_area(km2)]
Index: []

In [40]:
valores_nulos = df[df['gdp_per_capita'].isnull()]

valores_nulos.tail(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
2991,Slovakia,2001,0.00,6.00,9.65,17.10,5.08,69.682686,41766.94000,8.930000,unknown,0.0,NaN,114,49035.0
2992,Slovakia,2002,0.00,5.48,8.81,17.95,5.42,72.622750,42124.30000,8.610000,unknown,0.0,NaN,114,49035.0
2993,Slovakia,2003,0.00,5.35,9.52,17.86,3.58,69.250650,40913.17000,8.120000,unknown,0.0,NaN,114,49035.0
2994,Slovakia,2004,0.00,6.25,9.29,17.03,4.13,69.490970,40008.50800,7.600000,unknown,0.0,NaN,114,49035.0
2995,Slovakia,2005,0.00,6.31,8.93,17.73,4.68,71.506065,42086.47300,7.310000,unknown,0.0,NaN,114,49035.0
2996,Slovakia,2006,0.00,6.57,8.39,18.01,4.81,73.117590,40946.38300,6.670000,unknown,0.0,NaN,114,49035.0
2997,Slovakia,2007,0.00,8.23,7.57,15.33,4.93,72.799140,38418.40600,5.760000,unknown,0.0,NaN,114,49035.0
2998,Slovakia,2008,0.00,7.63,7.46,16.70,4.57,74.034110,39431.95000,5.600000,unknown,0.0,NaN,114,49035.0
2999,Slovakia,2009,0.00,10.00,6.89,14.08,4.92,73.387410,35687.54000,5.410000,unknown,0.0,NaN,114,49035.0
3000,Slovakia,2010,0.00,10.28,6.90,14.57,5.95,74.835884,38080.72700,5.450000,unknown,0.0,NaN,114,49035.0
3001,Slovakia,2011,0.00,10.36,7.80,15.41,5.00,72.350235,36591.31000,5.150000,unknown,0.0,NaN,114,49035.0
3002,Slovakia,2012,0.00,10.47,7.28,15.49,5.47,74.220960,35105.08600,4.860000,unknown,0.0,NaN,114,49035.0
3003,Slovakia,2013,0.00,10.68,6.36,15.72,6.36,77.637130,35936.51000,4.910000,unknown,0.0,NaN,114,49035.0
3004,Slovakia,2014,0.00,12.24,5.30,15.50,6.24,80.399410,33419.59400,4.500000,unknown,0.0,NaN,114,49035.0
3005,Slovakia,2015,0.00,13.41,5.34,15.15,6.05,79.879425,33734.29000,4.410000,unknown,0.0,NaN,114,49035.0
3006,Slovakia,2016,0.00,13.09,5.28,14.77,6.63,80.209890,34015.23400,4.350000,unknown,0.0,NaN,114,49035.0
3007,Slovakia,2017,0.00,12.43,5.67,15.08,6.54,79.223160,35774.91000,4.450000,unknown,0.0,NaN,114,49035.0
3008,Slovakia,2018,0.00,12.43,5.92,14.84,5.81,77.719230,35121.08600,4.280000,unknown,0.0,NaN,114,49035.0
3009,Slovakia,2019,0.00,17.64,6.26,15.28,6.65,77.793540,33892.78000,4.110000,unknown,0.0,NaN,114,49035.0
3010,Slovakia,2020,0.00,0.00,6.22,15.44,6.85,78.183090,33193.33000,0.000000,unknown,0.0,NaN,114,49035.0
3053,Somalia,2000,0.00,93.28,0.23,0.00,0.00,0.000000,340.10217,11.220000,490.0,0.0,NaN,25,637657.0
3054,Somalia,2001,0.00,93.26,0.25,0.00,0.00,0.000000,332.43317,11.320000,510.0,0.0,NaN,25,637657.0
3055,Somalia,2002,0.00,92.58,0.26,0.00,0.00,0.000000,346.37854,11.390000,569.999993,0.0,NaN,25,637657.0
3056,Somalia,2003,0.00,92.80,0.26,0.00,0.00,0.000000,334.05520,11.510000,579.999983,0.0,NaN,25,637657.0
3057,Somalia,2004,0.00,93.00,0.26,0.00,0.00,0.000000,322.42703,11.480000,579.999983,0.0,NaN,25,637657.0
3058,Somalia,2005,0.00,93.30,0.27,0.00,0.00,0.000000,314.66333,11.470000,579.999983,0.0,NaN,25,637657.0
3059,Somalia,2006,0.00,93.47,0.28,0.00,0.00,0.000000,307.72528,11.600000,579.999983,0.0,NaN,25,637657.0
3060,Somalia,2007,0.00,93.02,0.29,0.00,0.00,0.000000,302.79350,11.530000,620.000005,0.0,NaN,25,637657.0
3061,Somalia,2008,0.00,93.37,0.30,0.00,0.00,0.000000,291.03380,11.740000,620.000005,0.0,NaN,25,637657.0
3062,Somalia,2009,0.00,93.63,0.31,0.00,0.00,0.000000,283.20413,11.820000,610.000014,0.0,NaN,25,637657.0
3063,Somalia,2010,0.00,93.57,0.31,0.00,0.00,0.000000,283.12300,11.870000,629.999995,0.0,NaN,25,637657.0
3064,Somalia,2011,0.00,93.65,0.31,0.00,0.00,0.000000,278.71530,11.790000,629.999995,0.0,NaN,25,637657.0
3065,Somalia,2012,0.17,93.90,0.32,0.00,0.00,0.000000,274.60495,11.680000,629.999995,0.0,NaN,25,637657.0
3098,South Sudan,2016,0.04,28.79,0.49,0.00,0.00,0.000000,698.38540,0.000000,1730.000019,0.0,NaN,18,644329.0
3099,South Sudan,2017,0.04,28.63,0.51,0.00,0.00,0.000000,635.44260,0.000000,1519.999981,0.0,NaN,18,644329.0
3100,South Sudan,2018,0.05,28.65,0.55,0.00,0.01,1.785714,671.75750,0.000000,1549.999952,0.0,NaN,18,644329.0
3101,South Sudan,2019,0.06,26.65,0.55,0.00,0.01,1.785714,747.48596,0.000000,1700.000048,0.0,NaN,18,644329.0
3102,South Sudan,2020,0.06,0.00,0.53,0.00,0.01,1.851852,703.13510,0.000000,unknown,0.0,NaN,18,644329.0
3396,Turkmenistan,2020,0.20,0.00,20.11,0.00,0.00,0.000000,67626.92000,0.000000,unknown,0.0,NaN,13,488100.0
3586,Yemen,2000,0.00,0.95,3.21,0.00,0.00,0.000000,3228.21040,2.823132,unknown,0.0,NaN,56,527968.0
3587,Yemen,2001,0.00,0.89,3.42,0.00,0.00,0.000000,3380.40530,3.016477,unknown,0.0,NaN,56,527968.0
3588,Yemen,2002,0.00,0.90,3.54,0.00,0.00,0.000000,3320.32420,2.811401,unknown,0.0,NaN,56,527968.0
3589,Yemen,2003,0.00,0.78,3.85,0.00,0.00,0.000000,3707.22220,3.010832,unknown,0.0,NaN,56,527968.0
3590,Yemen,2004,0.00,0.75,4.10,0.00,0.00,0.000000,3811.39720,3.160727,unknown,0.0,NaN,56,527968.0
3591,Yemen,2005,0.00,0.74,4.48,0.00,0.00,0.000000,3906.30830,3.188304,unknown,0.0,NaN,56,527968.0
3592,Yemen,2006,0.00,0.76,5.06,0.00,0.00,0.000000,3788.24560,3.308474,unknown,0.0,NaN,56,527968.0
3593,Yemen,2007,0.00,0.76,5.67,0.00,0.00,0.000000,3902.28610,3.133247,unknown,0.0,NaN,56,527968.0
3594,Yemen,2008,0.04,0.74,6.15,0.00,0.00,0.000000,3976.89010,3.176676,unknown,0.0,NaN,56,527968.0
3595,Yemen,2009,0.04,0.70,6.34,0.00,0.00,0.000000,4277.22360,3.380211,unknown,0.0,NaN,56,527968.0
3596,Yemen,2010,0.04,0.78,7.29,0.00,0.00,0.000000,4030.75850,3.165451,unknown,0.0,NaN,56,527968.0
3597,Yemen,2011,0.05,0.93,5.83,0.00,0.00,0.000000,3289.45120,3.161177,unknown,0.0,NaN,56,527968.0
3598,Yemen,2012,0.06,1.08,6.65,0.00,0.00,0.000000,2769.04000,2.790347,unknown,0.0,NaN,56,527968.0
3599,Yemen,2013,0.09,0.76,7.99,0.00,0.00,0.000000,3797.82900,3.693557,unknown,0.0,NaN,56,527968.0
3600,Yemen,2014,0.19,0.76,7.19,0.00,0.01,0.138889,3495.32900,3.211405,unknown,0.0,NaN,56,527968.0
3601,Yemen,2015,2.26,1.96,5.81,0.00,0.12,2.023609,1837.10290,2.050356,unknown,0.0,NaN,56,527968.0
3602,Yemen,2016,2.94,2.48,4.36,0.00,0.16,3.539823,1432.55220,0.000000,unknown,0.0,NaN,56,527968.0
3603,Yemen,2017,3.59,2.80,3.63,0.00,0.19,4.973822,1288.87670,0.000000,unknown,0.0,NaN,56,527968.0
3604,Yemen,2018,8.77,3.60,2.82,0.00,0.48,14.545455,1170.72610,0.000000,unknown,0.0,NaN,56,527968.0
3605,Yemen,2019,8.57,3.11,2.93,0.00,0.48,14.076246,1475.98520,0.000000,unknown,0.0,NaN,56,527968.0
3606,Yemen,2020,8.48,0.00,2.74,0.00,0.49,15.170279,1092.00210,0.000000,unknown,0.0,NaN,56,527968.0

In [41]:
df['gdp_per_capita'] = df['gdp_per_capita'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.0,0.000000,0.000000,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.0,0.000000,0.000000,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,0.000000,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.00046,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.00015,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.00011,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.00023,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,unknown,-6.248748,1214.509820,38,390757.0

In [43]:
df.columns.value_counts()

country                                                             1
year                                                                1
renewable_electricity_generating_capacity_per_capita                1
renewable_energy_share_in_the_total_final_energy_consumption_(%)    1
electricity_from_fossil_fuels_(twh)                                 1
electricity_from_nuclear_(twh)                                      1
electricity_from_renewables_(twh)                                   1
low_carbon_electricity_(%_electricity)                              1
primary_energy_consumption_per_capita_(kwh/person)                  1
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         1
value_co2_emissions_kt_by_country                                   1
gdp_growth                                                          1
gdp_per_capita                                                      1
density\n(p/km2)                                                    1
land_area(km2)                                                      1
Name: count, dtype: int64

In [46]:
valores_nulos = df[df['land_area(km2)'].isnull()]

valores_nulos.tail(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
1218,French Guiana,2000,702.29,23.84,0.43,0.0,0.0,0.0,13692.394,0.0,unknown,0.0,0.0,NaN,NaN

In [47]:
nuevo_df = df[df['country'] == 'French Guiana']

nuevo_df.head(60)

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
1218,French Guiana,2000,702.29,23.84,0.43,0.0,0.0,0.0,13692.394,0.0,unknown,0.0,0.0,NaN,NaN

In [48]:
df['country'].value_counts()

country
Afghanistan      21
Oman             21
Netherlands      21
New Caledonia    21
New Zealand      21
                 ..
Zimbabwe         21
Serbia           14
Montenegro       14
South Sudan       8
French Guiana     1
Name: count, Length: 176, dtype: int64

In [49]:
df['land_area(km2)'] = df['land_area(km2)'].fillna(0)

df

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.0,0.000000,0.000000,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.0,0.000000,0.000000,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,0.000000,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3644,Zimbabwe,2016,62.88,81.90,3.50,0.0,3.32,48.680350,3227.68020,10.00,11020.00046,0.755869,1464.588957,38,390757.0
3645,Zimbabwe,2017,62.33,82.46,3.05,0.0,4.30,58.503407,3068.01150,9.51,10340.00015,4.709492,1235.189032,38,390757.0
3646,Zimbabwe,2018,82.53,80.23,3.73,0.0,5.46,59.412407,3441.98580,9.83,12380.00011,4.824211,1254.642265,38,390757.0
3647,Zimbabwe,2019,81.40,81.50,3.66,0.0,4.58,55.582527,3003.65530,10.47,11760.00023,-6.144236,1316.740657,38,390757.0
3648,Zimbabwe,2020,80.61,81.90,3.40,0.0,4.19,55.204216,2680.13180,10.00,unknown,-6.248748,1214.509820,38,390757.0

In [53]:
df = df.drop((['density(p/km2)']), axis=1)

df

KeyError: "['density(p/km2)'] not found in axis"

In [56]:
#df['density\n(p/km2)']

df.columns = df.columns.str.lower().str.replace('\n', '_')

In [67]:
df.rename(columns={'density\n(p/km2)': 'density_(p/km2)'}, inplace=True)

In [68]:
df.isna().sum()

country                                                             0
year                                                                0
renewable_electricity_generating_capacity_per_capita                0
renewable_energy_share_in_the_total_final_energy_consumption_(%)    0
electricity_from_fossil_fuels_(twh)                                 0
electricity_from_nuclear_(twh)                                      0
electricity_from_renewables_(twh)                                   0
low_carbon_electricity_(%_electricity)                              0
primary_energy_consumption_per_capita_(kwh/person)                  0
energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp)         0
value_co2_emissions_kt_by_country                                   0
gdp_growth                                                          0
gdp_per_capita                                                      0
density\n(p/km2)                                                    1
land_area(km2)                                                      0
dtype: int64

In [69]:
df.head()

,country,year,renewable_electricity_generating_capacity_per_capita,renewable_energy_share_in_the_total_final_energy_consumption_(%),electricity_from_fossil_fuels_(twh),electricity_from_nuclear_(twh),electricity_from_renewables_(twh),low_carbon_electricity_(%_electricity),primary_energy_consumption_per_capita_(kwh/person),energy_intensity_level_of_primary_energy_(mj/$2017_ppp_gdp),value_co2_emissions_kt_by_country,gdp_growth,gdp_per_capita,density\n(p/km2),land_area(km2)
0,Afghanistan,2000,9.22,44.99,0.16,0.0,0.31,65.957440,302.59482,1.64,760.0,0.000000,0.000000,60,652230.0
1,Afghanistan,2001,8.86,45.60,0.09,0.0,0.50,84.745766,236.89185,1.74,730.0,0.000000,0.000000,60,652230.0
2,Afghanistan,2002,8.47,37.83,0.13,0.0,0.56,81.159424,210.86215,1.40,1029.999971,0.000000,179.426579,60,652230.0
3,Afghanistan,2003,8.09,36.66,0.31,0.0,0.63,67.021280,229.96822,1.40,1220.000029,8.832278,190.683814,60,652230.0
4,Afghanistan,2004,7.75,44.24,0.33,0.0,0.56,62.921350,204.23125,1.20,1029.999971,1.414118,211.382074,60,652230.0

In [ ]:
nuevo_df = df[df['year'] == 2020]

nuevo_df.head(60)

In [ ]:
df.isna().sum()